import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'si' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Dictionary of translations for static UI elements
const uiTranslations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    home: 'Home',
    features: 'Features',
    about: 'About',
    dashboard: 'Dashboard',
    scan_disease: 'Scan Disease',
    crops: 'Crops',
    knowledge_base: 'Knowledge Base',
    admin: 'Admin',
    login: 'Login',
    get_started: 'Get Started',
    profile: 'Profile',
    sign_out: 'Sign Out',
    admin_panel: 'Admin Panel',

    // Landing Page
    hero_title: 'Detect Crop Diseases Instantly with AI',
    hero_subtitle: 'Upload a crop image and receive disease diagnosis and treatment recommendations specifically designed for Sri Lankan farming conditions.',
    get_started_free: 'Get Started Free',
    learn_more: 'Learn More',
    made_for_sl: 'Made for Sri Lankan Farmers',
    disease_detected: 'Disease Detected',
    accuracy_title: '98% Accuracy',
    diseases_covered_title: '15+ Diseases',
    how_it_works: 'How It Works',
    how_it_works_sub: 'Three simple steps to protect your crops',
    step1_title: 'Upload Image',
    step1_desc: 'Take a photo of your affected crop and upload it to our system',
    step2_title: 'Get Diagnosis',
    step2_desc: 'Our AI analyzes the image and identifies the disease within seconds',
    step3_title: 'Follow Treatment',
    step3_desc: 'Receive detailed treatment recommendations with local availability',
    supported_crops: 'Supported Crops',
    supported_crops_sub: 'Our system can detect diseases in these common Sri Lankan crops',
    why_choose: 'Why Choose CropGuard?',
    benefit1: 'Instant disease identification using AI',
    benefit2: 'Treatment recommendations in Sinhala and Tamil',
    benefit3: 'Organic and chemical treatment options',
    benefit4: 'Works offline after first load',
    benefit5: 'Free for all Sri Lankan farmers',
    benefit6: 'Regularly updated disease database',
    feature_ai_detection_title: 'AI Disease Detection',
    feature_ai_detection_desc: 'Upload a photo of your crop and our AI instantly identifies diseases with high accuracy using advanced machine learning.',
    feature_localized_treatment_title: 'Localized Treatment',
    feature_localized_treatment_desc: 'Get treatment recommendations specifically for Sri Lanka, with locally available products and suppliers.',
    feature_prevention_tips_title: 'Prevention Tips',
    feature_prevention_tips_desc: 'Learn how to prevent diseases before they occur with practical farming advice tailored to local conditions.',
    feature_history_tracking_title: 'History Tracking',
    feature_history_tracking_desc: 'Keep track of all your disease scans and treatments to monitor your farm health over time.',
    major_crops: 'Major Crops',
    districts_covered: 'Districts Covered',
    accuracy_rate: 'Accuracy Rate',
    cta_title: 'Start Protecting Your Crops Today',
    cta_desc: 'Join thousands of Sri Lankan farmers who trust CropGuard for their crop health management',
    create_free_account: 'Create Free Account',

    // Dashboard
    welcome_back: 'Welcome back',
    dashboard_desc: 'Monitor your crop health and recent scans',
    recent_scans: 'Recent Scans',
    view_all: 'View All',
    no_scans: 'No scans recorded yet',
    start_scanning: 'Start Scanning Now',
    total_scans: 'Total Scans',
    diseases_found: 'Diseases Found',
    healthy_plants: 'Healthy Plants',
    quick_stats: 'Quick Statistics',

    // Disease Detection Page
    disease_detection_title: 'Disease Detection',
    disease_detection_desc: 'Upload an image of your crop to detect diseases',
    select_crop_type: 'Select Crop Type',
    choose_a_crop: 'Choose a crop',
    upload_crop_image: 'Upload Crop Image',
    drag_drop_image: 'Drag & drop image here',
    or: 'or',
    choose_image: 'Choose Image',
    ready_for_analysis: 'Image ready for analysis',
    start_disease_scan: 'Start Disease Scan',
    analyzing_image: 'Analyzing Image...',
    tips_title: 'Tips for better detection:',
    tip1: 'Take clear, well-lit photos of affected plant parts',
    tip2: 'Include close-ups of visible symptoms (spots, discoloration)',
    tip3: 'Ensure the affected area is clearly visible in the image',
    tip4: 'Avoid blurry or dark images for best results',

    // Detection Result Page
    scan_results: 'Scan Results',
    crop_name: 'Crop Name',
    detected_disease: 'Detected Disease',
    confidence_score: 'Confidence Score',
    severity: 'Severity',
    scan_date: 'Scan Date',
    view_recommendations: 'View Treatment Recommendations',
    healthy_desc: 'Great news! Your crop appears to be healthy.',
    diagnosed_disease: 'Diagnosed Disease',

    // Treatment Page
    back_to_detection: 'Back to Detection',
    symptoms: 'Symptoms',
    organic_treatment: 'Organic Treatment',
    chemical_treatment: 'Chemical Treatment',
    recommended_dosage: 'Recommended Dosage',
    application_method: 'Application Method',
    available_in_sl: 'Available in Sri Lanka',
    safety_precautions: 'Safety Precautions',
    prevention_tips: 'Prevention Tips',
    quick_actions: 'Quick Actions',
    scan_another_crop: 'Scan Another Crop',
    view_history: 'View History',
    browse_diseases: 'Browse Diseases',
    need_help: 'Need Help?',
    help_desc: 'Contact your local agricultural extension officer for personalized advice.',
    hotline: 'Department of Agriculture Hotline: 1920',
    welcome_back_title: 'Welcome Back',
    login_desc: 'Sign in to continue protecting your crops',
    email_label: 'Email',
    password_label: 'Password',
    remember_me: 'Remember me',
    forgot_password: 'Forgot password?',
    forgot_password_title: 'Reset Password',
    forgot_password_desc: 'Enter your email to receive a password reset link.',
    reset_email_sent: 'Password reset email sent. Please check your inbox.',
    sending: 'Sending...',
    reset_password_btn: 'Send Reset Link',
    back_to_login: 'Back to Login',
    sign_in_btn: 'Sign In',
    signing_in: 'Signing in...',
    dont_have_account: "Don't have an account?",
    sign_up_link: 'Sign up',
    agree_terms: 'By signing in, you agree to our Terms of Service and Privacy Policy',
    create_account: 'Create Your Account',
    join_farmers: 'Join thousands of Sri Lankan farmers',
    full_name_label: 'Full Name',
    phone_label: 'Mobile Number (Optional)',
    district_label: 'District',
    confirm_password_label: 'Confirm Password',
    creating_account: 'Creating Account...',
    create_account_btn: 'Create Account',
    already_have_account: 'Already have an account?',
    sign_in_link: 'Sign in',
    agree_terms_register: 'By creating an account, you agree to our Terms of Service and Privacy Policy',
    profile_settings: 'Profile Settings',
    personal_info: 'Personal Information',
    change_password: 'Change Password',
    save_changes: 'Save Changes',
    saving_changes: 'Saving Changes...',
    cancel_btn: 'Cancel',
    update_password: 'Update Password',
    password_security_desc: 'Keep your account secure by using a strong, unique password.',
    account_created_on: 'Account created on',
    scan_disease_desc: 'Upload an image to detect crop diseases',
    view_history_btn: 'View History',
    view_history_desc: 'See all your previous scans',
    crops_desc: 'Learn about crop varieties',
    knowledge_base_desc: 'Browse disease information',
    today: 'Today',
    quick_actions_title: 'Quick Actions',
    weak: 'Weak',
    medium: 'Medium',
    strong: 'Strong',
    password_strength: 'Password strength',
    passwords_dont_match: 'Passwords do not match',
    password_too_short: 'Password must be at least 6 characters',
    select_district: 'Please select your district',
    account_created: 'Account Created!',
    redirecting_login: 'Redirecting you to login...',
    select_district_placeholder: 'Select your district',
    profile_updated_success: 'Profile updated successfully!',
    new_passwords_dont_match: 'New passwords do not match',
    password_changed_success: 'Password changed successfully!',
    back_to_dashboard: 'Back to Dashboard',
    new_password_label: 'New Password',
    confirm_new_password_label: 'Confirm New Password',
    search_crops: 'Search crops...',
    diseases_label: 'diseases',
    growing_guide_title: 'Growing Guide',
    sunlight: 'Sunlight',
    sunlight_desc: '6-8 hours daily',
    watering: 'Watering',
    watering_desc: 'Regular, moderate',
    temperature: 'Temperature',
    temperature_desc: '25-35°C ideal',
    prevention_tips_avail: 'Prevention tips available',
    common_diseases: 'Common Diseases',
    kb_subtitle: 'Browse diseases, symptoms, and treatments',
    search_diseases_placeholder: 'Search diseases or symptoms...',
    all_crops: 'All Crops',
    all_severity: 'All Severity',
    found: 'Found',
    filters: 'Filters',
    no_diseases_found: 'No diseases found',
    adjust_filters: 'Try adjusting your search or filters',
    causes_label: 'Causes:',
    view_treatment_btn: 'View Treatment',
    need_expert_advice: 'Need Expert Advice?',
    website_label: 'Website:',
    hotline_label: 'Hotline:',
    recommended_treatments: 'Recommended Treatments',
    treatment_available: 'Treatment Available',
    treatment_available_desc: 'Get detailed treatment recommendations including organic treatments, chemical options, and locally available products in Sri Lanka.',
    detection_history: 'Detection History',
    detection_history_desc: 'View and manage your scan history',
    export_csv: 'Export CSV',
    search_history_placeholder: 'Search by disease name...',
    clear_btn: 'Clear',
    no_detections_found: 'No detections found',
    adjust_filters_history: 'Try adjusting your filters',
    start_scanning_history: 'Start scanning crops to see your history',
    start_scanning_btn: 'Start Scanning',
    date: 'Date',
    actions: 'Actions',
    select_crop_alert: 'Please select a crop type from the dropdown above before starting the scan.',
    sign_in_alert: 'Please sign in to save scan results.',
    process_image_error: 'Failed to process image. Please try again.',
    supports_formats: 'Supports: JPG, PNG, WEBP (Max 10MB)',
    good_morning: 'Good morning',
    good_afternoon: 'Good afternoon',
    good_evening: 'Good evening',
    email_unchangeable: 'Email cannot be changed',
    invalid_credentials_error: 'Invalid email or password',
  },
  si: {
    // Navbar
    home: 'මුල් පිටුව',
    features: 'විශේෂාංග',
    about: 'අප ගැන',
    dashboard: 'දත්ත පුවරුව',
    scan_disease: 'රෝගය පරිලෝකනය කරන්න',
    crops: 'බෝග වර්ග',
    knowledge_base: 'දැනුම් පද්ධතිය',
    admin: 'පරිපාලක',
    login: 'ඇතුල් වන්න',
    get_started: 'ආරම්භ කරන්න',
    profile: 'ප්‍රොෆයිලය',
    sign_out: 'නික්ම යන්න',
    admin_panel: 'පරිපාලන පුවරුව',

    // Landing Page
    hero_title: 'බෝග රෝග AI තාක්ෂණයෙන් ක්ෂණිකව හඳුනාගන්න',
    hero_subtitle: 'ශ්‍රී ලංකාවේ වගා තත්ත්වයන්ට ගැලපෙන පරිදි සකසන ලද රෝග විනිශ්චය සහ ප්‍රතිකාර නිර්දේශ ලබා ගැනීමට බෝගයේ ඡායාරූපයක් එක් කරන්න.',
    get_started_free: 'නොමිලේ ආරම්භ කරන්න',
    learn_more: 'වැඩි විස්තර',
    made_for_sl: 'ශ්‍රී ලාංකීය ගොවීන් සඳහාම නිපදවන ලදි',
    disease_detected: 'හඳුනාගත් රෝගය',
    accuracy_title: '98% නිරවද්‍යතාවය',
    diseases_covered_title: 'රෝග 15+ කට වඩා',
    how_it_works: 'ක්‍රියා කරන ආකාරය',
    how_it_works_sub: 'ඔබේ බෝග ආරක්ෂා කිරීමට සරල පියවර තුනක්',
    step1_title: 'ඡායාරූපයක් එක් කරන්න',
    step1_desc: 'රෝගී වූ බෝගයේ පැහැදිලි ඡායාරූපයක් ගෙන අපගේ පද්ධතියට එක් කරන්න',
    step2_title: 'රෝග විනිශ්චය ලබා ගන්න',
    step2_desc: 'අපගේ AI තාක්ෂණය තත්පර කිහිපයකින් රෝගය හඳුනා ගනී',
    step3_title: 'ප්‍රතිකාර පිළිපදින්න',
    step3_desc: 'දේශීයව මිලදී ගත හැකි ද්‍රව්‍ය සහිත සවිස්තරාත්මක ප්‍රතිකාර නිර්දේශ ලබා ගන්න',
    supported_crops: 'සහාය දක්වන බෝග',
    supported_crops_sub: 'ශ්‍රී ලංකාවේ බහුලව වගා කරන මෙම බෝගයන්හි රෝග හඳුනාගත හැක',
    why_choose: 'ඇයි CropGuard තෝරාගන්නේ?',
    benefit1: 'AI භාවිතයෙන් ක්ෂණිකව බෝග රෝග හඳුනා ගැනීම',
    benefit2: 'සිංහල සහ දෙමළ භාෂාවලින් ප්‍රතිකාර නිර්දේශ',
    benefit3: 'කාබනික සහ රසායනික ප්‍රතිකාර ක්‍රම',
    benefit4: 'පළමු වරට පසුව අන්තර්ජාලය නොමැතිව ක්‍රියා කරයි (Offline)',
    benefit5: 'ශ්‍රී ලාංකීය ගොවීන්ට සම්පූර්ණයෙන්ම නොමිලේ',
    benefit6: 'නිරන්තරයෙන් යාවත්කාලීන වන රෝග දත්ත ගබඩාව',
    feature_ai_detection_title: 'AI මගින් රෝග හඳුනාගැනීම',
    feature_ai_detection_desc: 'ඔබේ බෝගයේ ඡායාරූපයක් උඩුගත කර, AI මගින් උසස් නිරවද්‍යතාවයකින් රෝග හඳුනා ගන්න.',
    feature_localized_treatment_title: 'දේශීය ප්‍රතිකාර නිර්දේශ',
    feature_localized_treatment_desc: 'ශ්‍රී ලංකාව සඳහා සකස් කළ ප්‍රතිකාර නිර්දේශ ලබා ගන්න, දේශීයව ලැබෙන ද්‍රව්‍ය සහ සැපයුම්කරුවන් සමඟ.',
    feature_prevention_tips_title: 'වැළැක්වීමේ උපදෙස්',
    feature_prevention_tips_desc: 'රෝග සිදුවීමට පෙර එය වැළැක්වීම සඳහා ප්‍රායෝගික ගොවීන්ට සකස් කළ උපදෙස් ඉගෙන ගන්න.',
    feature_history_tracking_title: 'ඉතිහාසය නිරීක්ෂණය',
    feature_history_tracking_desc: 'සියලු රෝග සෙවීම් සහ ප්‍රතිකාර ඔබේ ගොවි සෞඛ්‍යය නිරීක්ෂණය කිරීමට නිරීක්ෂණය කරන්න.',
    major_crops: 'ප්‍රධාන බෝග',
    districts_covered: 'දිස්ත්‍රික්ක',
    accuracy_rate: 'නිරවද්‍යතාවය',
    cta_title: 'අදම ඔබේ වගාවන් ආරක්ෂා කරගැනීම අරඹන්න',
    cta_desc: 'බෝග සෞඛ්‍ය කළමනාකරණය සඳහා CropGuard විශ්වාස කරන දහස් ගණන් ශ්‍රී ලාංකීය ගොවීන් සමඟ එක්වන්න',
    create_free_account: 'නොමිලේ ගිණුමක් අරඹන්න',

    // Dashboard
    welcome_back: 'නැවත සාදරයෙන් පිළිගනිමු',
    dashboard_desc: 'ඔබේ බෝග සෞඛ්‍යය සහ මෑතකදී කළ පරිලෝකන නිරීක්ෂණය කරන්න',
    recent_scans: 'මෑතකදී කළ පරිලෝකන',
    view_all: 'සියල්ල බලන්න',
    no_scans: 'තවමත් පරිලෝකන කිසිවක් සිදුකර නැත',
    start_scanning: 'දැන්ම පරිලෝකනය කරන්න',
    total_scans: 'මුළු පරිලෝකන සංඛ්‍යාව',
    diseases_found: 'හඳුනාගත් රෝග',
    healthy_plants: 'නිරෝගී ශාක',
    quick_stats: 'කෙටි සංඛ්‍යාලේඛන',

    // Disease Detection Page
    disease_detection_title: 'රෝග හඳුනාගැනීම',
    disease_detection_desc: 'රෝගය හඳුනාගැනීම සඳහා බෝගයේ ඡායාරූපයක් එක් කරන්න',
    select_crop_type: 'බෝග වර්ගය තෝරන්න',
    choose_a_crop: 'බෝගයක් තෝරන්න',
    upload_crop_image: 'බෝගයේ ඡායාරූපයක් එක් කරන්න',
    drag_drop_image: 'ඡායාරූපය මෙතැනට ඇද දමන්න (Drag & drop)',
    or: 'නැතහොත්',
    choose_image: 'ඡායාරූපය තෝරන්න',
    ready_for_analysis: 'ඡායාරූපය විශ්ලේෂණයට සූදානම්',
    start_disease_scan: 'රෝගය හඳුනාගැනීම අරඹන්න',
    analyzing_image: 'ඡායාරූපය විශ්ලේෂණය කරමින්...',
    tips_title: 'නිවැරදිව රෝගය හඳුනාගැනීම සඳහා උපදෙස්:',
    tip1: 'රෝගී වූ ශාක කොටස්වල පැහැදිලි, ආලෝකය සහිත ඡායාරූප ගන්න',
    tip2: 'ලප, දුර්වර්ණ වීම් වැනි රෝග ලක්ෂණ ලඟින් ඡායාරූපයට නගන්න',
    tip3: 'රෝගී ප්‍රදේශය ඡායාරූපයේ පැහැදිලිව පෙනෙන බව තහවුරු කරගන්න',
    tip4: 'පැහැදිලි නොවන හෝ අඳුරු ඡායාරූප භාවිතයෙන් වලකින්න',

    // Detection Result Page
    scan_results: 'පරිලෝකන ප්‍රතිඵල',
    crop_name: 'බෝගයේ නම',
    detected_disease: 'හඳුනාගත් රෝගය',
    confidence_score: 'නිරවද්‍යතා ප්‍රතිශතය',
    severity: 'දරුණුතාවය',
    scan_date: 'පරිලෝකනය කළ දිනය',
    view_recommendations: 'ප්‍රතිකාර නිර්දේශයන් බලන්න',
    healthy_desc: 'සුභ ආරංචියක්! ඔබේ බෝගය නිරෝගී මට්ටමේ පවතී.',
    diagnosed_disease: 'හඳුනාගත් රෝගය',

    // Treatment Page
    back_to_detection: 'නැවත පරිලෝකනයට',
    symptoms: 'රෝග ලක්ෂණ',
    organic_treatment: 'කාබනික ප්‍රතිකාර',
    chemical_treatment: 'රසායනික ප්‍රතිකාර',
    recommended_dosage: 'නිර්දේශිත මාත්‍රාව',
    application_method: 'භාවිතා කරන ආකාරය',
    available_in_sl: 'ශ්‍රී ලංකාවේ ලබාගත හැකි වෙළඳ නාම',
    safety_precautions: 'ආරක්ෂිත පියවර',
    prevention_tips: 'වැළැක්වීමේ පියවර',
    quick_actions: 'ක්ෂණික ක්‍රියාමාර්ග',
    scan_another_crop: 'තවත් බෝගයක් පරීක්ෂා කරන්න',
    view_history: 'ඉතිහාසය බලන්න',
    browse_diseases: 'රෝග පිළිබඳ තොරතුරු',
    need_help: 'උපකාර අවශ්‍යද?',
    help_desc: 'පුද්ගලික උපදෙස් සඳහා ඔබේ ප්‍රාදේශීය කෘෂිකර්ම නිලධාරීවරයා අමතන්න.',
    hotline: 'කෘෂිකර්ම දෙපාර්තමේන්තු ක්ෂණික ඇමතුම් අංකය: 1920',
    welcome_back_title: 'නැවත සාදරයෙන් පිළිගනිමු',
    login_desc: 'ඔබේ වගාවන් ආරක්ෂා කර ගැනීමට ඇතුල් වන්න',
    email_label: 'විද්‍යුත් තැපෑල (Email)',
    password_label: 'මුරපදය (Password)',
    remember_me: 'මාව මතක තබා ගන්න',
    forgot_password: 'මුරපදය අමතකද?',
    forgot_password_title: 'මුරපදය නැවත සකසන්න',
    forgot_password_desc: 'මුරපදය නැවත සැකසීමේ සබැඳිය ලබා ගැනීමට ඔබේ විද්‍යුත් තැපෑල ඇතුළත් කරන්න.',
    reset_email_sent: 'මුරපදය නැවත සැකසීමේ විද්‍යුත් තැපෑල යවා ඇත. කරුණාකර ඔබගේ Inbox එක පරීක්ෂා කරන්න.',
    sending: 'යවමින්...',
    reset_password_btn: 'මුරපදය නැවත සැකසීමේ සබැඳියක් යවන්න',
    back_to_login: 'නැවත ඇතුල් වීමේ පිටුවට',
    sign_in_btn: 'ඇතුල් වන්න',
    signing_in: 'ඇතුල් වෙමින්...',
    dont_have_account: 'ගිණුමක් නොමැතිද?',
    sign_up_link: 'ලියාපදිංචි වන්න',
    agree_terms: 'ඇතුල් වීමෙන්, ඔබ අපගේ සේවා නියම සහ රහස්‍යතා ප්‍රතිපත්තියට එකඟ වේ',
    create_account: 'ගිණුමක් සාදන්න',
    join_farmers: 'දහස් ගණන් ශ්‍රී ලාංකීය ගොවීන් සමඟ එක්වන්න',
    full_name_label: 'සම්පූර්ණ නම',
    phone_label: 'ජංගම දුරකථන අංකය (විකල්ප)',
    district_label: 'දිස්ත්‍රික්කය',
    confirm_password_label: 'මුරපදය තහවුරු කරන්න',
    creating_account: 'ගිණුම සාදමින්...',
    create_account_btn: 'ගිණුම සාදන්න',
    already_have_account: 'දැනටමත් ගිණුමක් තිබේද?',
    sign_in_link: 'ඇතුල් වන්න',
    agree_terms_register: 'ගිණුමක් සෑදීමෙන්, ඔබ අපගේ සේවා නියම සහ රහස්‍යතා ප්‍රතිපත්තියට එකඟ වේ',
    profile_settings: 'ප්‍රොෆයිල් සැකසුම්',
    personal_info: 'පෞද්ගලික තොරතුරු',
    change_password: 'මුරපදය වෙනස් කරන්න',
    save_changes: 'සැකසුම් සුරකින්න',
    saving_changes: 'සුරකිමින්...',
    cancel_btn: 'අවලංගු කරන්න',
    update_password: 'මුරපදය යාවත්කාලීන කරන්න',
    password_security_desc: 'ශක්තිමත්, අනන්‍ය මුරපදයක් භාවිතයෙන් ඔබේ ගිණුම ආරක්ෂිතව තබා ගන්න.',
    account_created_on: 'ගිණුම සෑදූ දිනය',
    scan_disease_desc: 'රෝග හඳුනාගැනීම සඳහා ඡායාරූපයක් එක් කරන්න',
    view_history_btn: 'ඉතිහාසය බලන්න',
    view_history_desc: 'ඔබගේ පෙර පරිලෝකන සියල්ල බලන්න',
    crops_desc: 'බෝග වර්ග පිළිබඳව ඉගෙන ගන්න',
    knowledge_base_desc: 'බෝග රෝග තොරතුරු පිරික්සන්න',
    today: 'අද දින',
    quick_actions_title: 'ක්ෂණික ක්‍රියාමාර්ග',
    weak: 'දුර්වල',
    medium: 'මධ්‍යම',
    strong: 'ශක්තිමත්',
    password_strength: 'මුරපද ශක්තිමත්භාවය',
    passwords_dont_match: 'මුරපද එකිනෙකට නොගැලපේ',
    password_too_short: 'මුරපදය අවම වශයෙන් අක්ෂර 6ක් විය යුතුය',
    select_district: 'කරුණාකර ඔබගේ දිස්ත්‍රික්කය තෝරන්න',
    account_created: 'ගිණුම සාදන ලදී!',
    redirecting_login: 'ඇතුල් වීමේ පිටුවට යොමු කරමින්...',
    select_district_placeholder: 'දිස්ත්‍රික්කය තෝරන්න',
    profile_updated_success: 'ප්‍රොෆයිලය සාර්ථකව යාවත්කාලීන කරන ලදී!',
    new_passwords_dont_match: 'නව මුරපද ගැලපෙන්නේ නැත',
    password_changed_success: 'මුරපදය සාර්ථකව වෙනස් කරන ලදී!',
    back_to_dashboard: 'නැවත දත්ත පුවරුවට',
    new_password_label: 'නව මුරපදය',
    confirm_new_password_label: 'නව මුරපදය තහවුරු කරන්න',
    search_crops: 'බෝග සොයන්න...',
    diseases_label: 'රෝග',
    growing_guide_title: 'වගා උපදෙස්',
    sunlight: 'හිරු එළිය',
    sunlight_desc: 'දිනපතා පැය 6-8',
    watering: 'ජල සම්පාදනය',
    watering_desc: 'නිතිපතා, මධ්‍යම ප්‍රමාණයෙන්',
    temperature: 'උෂ්ණත්වය',
    temperature_desc: 'සෙල්සියස් 25-35 උචිතයි',
    prevention_tips_avail: 'වැළැක්වීමේ උපදෙස් තිබේ',
    common_diseases: 'පොදු බෝග රෝග',
    kb_subtitle: 'බෝග රෝග, ලක්ෂණ සහ ප්‍රතිකාර පිරික්සන්න',
    search_diseases_placeholder: 'රෝග හෝ රෝග ලක්ෂණ සොයන්න...',
    all_crops: 'සියලුම බෝග',
    all_severity: 'සියලුම දරුණුතා',
    found: 'හමු විය',
    filters: 'පෙරහන්',
    no_diseases_found: 'රෝග කිසිවක් හමු නොවීය',
    adjust_filters: 'ඔබේ සෙවුම හෝ පෙරහන් වෙනස් කර උත්සාහ කරන්න',
    causes_label: 'හේතු:',
    view_treatment_btn: 'ප්‍රතිකාර බලන්න',
    need_expert_advice: 'විශේෂඥ උපදෙස් අවශ්‍යද?',
    website_label: 'වෙබ් අඩවිය:',
    hotline_label: 'ක්ෂණික ඇමතුම:',
    recommended_treatments: 'ප්‍රතිකාර නිර්දේශ',
    treatment_available: 'ප්‍රතිකාර ලබාගත හැක',
    treatment_available_desc: 'කාබනික ප්‍රතිකාර, රසායනික ක්‍රම සහ ශ්‍රී ලංකාව තුළ දේශීයව ලබාගත හැකි නිෂ්පාදන ඇතුළුව සවිස්තරාත්මක ප්‍රතිකාර නිර්දේශ ලබා ගන්න.',
    detection_history: 'පරිලෝකන ඉතිහාසය',
    detection_history_desc: 'ඔබගේ පෙර පරිලෝකන ඉතිහාසය බලන්න',
    export_csv: 'CSV අපනයනය කරන්න',
    search_history_placeholder: 'රෝගයේ නමින් සොයන්න...',
    clear_btn: 'පිරිසිදු කරන්න',
    no_detections_found: 'පරිලෝකන කිසිවක් හමු නොවීය',
    adjust_filters_history: 'ඔබේ පෙරහන් වෙනස් කර උත්සාහ කරන්න',
    start_scanning_history: 'ඔබගේ ඉතිහාසය දැකීමට බෝග පරිලෝකනය කිරීම ආරම්භ කරන්න',
    start_scanning_btn: 'පරිලෝකනය අරඹන්න',
    date: 'දිනය',
    actions: 'ක්‍රියා',
    select_crop_alert: 'පරිලෝකනය ආරම්භ කිරීමට පෙර කරුණාකර ඉහත පතන මෙනුවෙන් බෝග වර්ගයක් තෝරන්න.',
    sign_in_alert: 'පරිලෝකන ප්‍රතිඵල සුරැකීමට කරුණාකර ඇතුල් වන්න.',
    process_image_error: 'ඡායාරූපය විශ්ලේෂණය කිරීම අසාර්ථක විය. කරුණාකර නැවත උත්සාහ කරන්න.',
    supports_formats: 'ගොනු ආකෘති: JPG, PNG, WEBP (උපරිම 10MB)',
    good_morning: 'සුභ උදෑසනක්',
    good_afternoon: 'සුභ පස්වරුවක්',
    good_evening: 'සුභ සැන්දෑවක්',
    email_unchangeable: 'විද්‍යුත් තැපෑල වෙනස් කළ නොහැක',
    invalid_credentials_error: 'විද්‍යුත් තැපෑල හෝ මුරපදය වැරදිය',
  },
  ta: {
    // Navbar
    home: 'முகப்பு',
    features: 'அம்சங்கள்',
    about: 'எங்களைப் பற்றி',
    dashboard: 'தகவல் பலகை',
    scan_disease: 'நோய் கண்டறிதல்',
    crops: 'பயிர்கள்',
    knowledge_base: 'அறிவுத் தளம்',
    admin: 'நிர்வாகி',
    login: 'உள்நுழைக',
    get_started: 'தொடங்குக',
    profile: 'சுயவிவரம்',
    sign_out: 'வெளியேறு',
    admin_panel: 'நிர்வாக பலகை',

    // Landing Page
    hero_title: 'பயிர் நோய்களை AI மூலம் உடனடியாகக் கண்டறியவும்',
    hero_subtitle: 'பயிர் படத்தை பதிவேற்றி, இலங்கை விவசாய நிலைமைகளுக்கு ஏற்ப வடிவமைக்கப்பட்ட நோய் கண்டறிதல் மற்றும் சிகிச்சை பரிந்துரைகளைப் பெறுங்கள்.',
    get_started_free: 'இலவசமாகத் தொடங்குங்கள்',
    learn_more: 'மேலும் அறிய',
    made_for_sl: 'இலங்கை விவசாயிகளுக்காக உருவாக்கப்பட்டது',
    disease_detected: 'கண்டறியப்பட்ட நோய்',
    accuracy_title: '98% துல்லியம்',
    diseases_covered_title: '15+ நோய்கள்',
    how_it_works: 'இது எப்படி வேலை செய்கிறது',
    how_it_works_sub: 'உங்கள் பயிர்களைப் பாதுகாக்க மூன்று எளிய வழிமுறைகள்',
    step1_title: 'படத்தை பதிவேற்றவும்',
    step1_desc: 'பாதிக்கப்பட்ட பயிரின் புகைப்படத்தை எடுத்து எங்கள் அமைப்பில் பதிவேற்றவும்',
    step2_title: 'கண்டறிதலைப் பெறுங்கள்',
    step2_desc: 'எங்கள் AI தொழில்நுட்பம் சில நொடிகளில் நோயைக் கண்டறியும்',
    step3_title: 'சிகிச்சையைப் பின்பற்றுங்கள்',
    step3_desc: 'உள்ளூரில் கிடைக்கக்கூடிய தயாரிப்புகளுடன் விரிவான சிகிச்சை பரிந்துரைகளைப் பெறுங்கள்',
    supported_crops: 'ஆதரவு பயிர்கள்',
    supported_crops_sub: 'இலங்கையில் பொதுவாக பயிரிடப்படும் இந்த பயிர்களில் உள்ள நோய்களை எங்கள் அமைப்பு கண்டறியும்',
    why_choose: 'ஏன் CropGuard ஐ தேர்வு செய்ய வேண்டும்?',
    benefit1: 'AI தொழில்நுட்பம் மூலம் உடனடி நோய் கண்டறிதல்',
    benefit2: 'சிங்களம் மற்றும் தமிழ் மொழிகளில் சிகிச்சை பரிந்துரைகள்',
    benefit3: 'இயற்கை மற்றும் இரசாயன சிகிச்சை முறைகள்',
    benefit4: 'முதல் முறைக்கு பின் இணையம் இல்லாமல் வேலை செய்யும் (Offline)',
    benefit5: 'இலங்கை விவசாயிகளுக்கு முற்றிலும் இலவசம்',
    benefit6: 'தொடர்ந்து புதுப்பிக்கப்படும் நோய் தரவுத்தளம்',
    feature_ai_detection_title: 'AI மூலம் நோய் கண்டறிதல்',
    feature_ai_detection_desc: 'உங்கள் பயிரின் புகைப்படத்தை பதிவேற்றி, AI மூலம் உயர்ந்த துல்லியத்துடன் நோய்களைக் கண்டறியவும்.',
    feature_localized_treatment_title: 'உள்ளூர் சிகிச்சை பரிந்துரைகள்',
    feature_localized_treatment_desc: 'இலங்கைக்கு குறிப்பாக பொருத்தமான சிகிச்சை பரிந்துரைகளையும், உள்ளூர் தயாரிப்புகள் மற்றும் சப்ளையர்களையும் பெறுங்கள்.',
    feature_prevention_tips_title: 'தடுப்பு குறிப்புகள்',
    feature_prevention_tips_desc: 'நோய்கள் ஏற்படுவதற்கு முன்பு அவற்றை தடுப்பதற்கான நடைமுறை விவசாய ஆலோசனைகளை அறிக.',
    feature_history_tracking_title: 'வரலாறு கண்காணிப்பு',
    feature_history_tracking_desc: 'உங்கள் அனைத்து நோய் சோதனைகள் மற்றும் சிகிச்சை வரலாற்றையும் கண்காணித்து உங்கள் பண்ணை ஆரோக்கியத்தைப் பின்தொடருங்கள்.',
    major_crops: 'முக்கிய பயிர்கள்',
    districts_covered: 'மாவட்டங்கள்',
    accuracy_rate: 'துல்லியம்',
    cta_title: 'இன்றே உங்கள் பயிர்களைப் பாதுகாக்கத் தொடங்குங்கள்',
    cta_desc: 'பயிர் சுகாதார மேலாண்மைக்கு CropGuard ஐ நம்பும் ஆயிரக்கணக்கான இலங்கை விவசாயிகளுடன் இணையுங்கள்',
    create_free_account: 'இலவச கணக்கை உருவாக்குங்கள்',

    // Dashboard
    welcome_back: 'மீண்டும் வரவேற்கிறோம்',
    dashboard_desc: 'உங்கள் பயிர் ஆரோக்கியத்தையும் சமீபத்திய சோதனைகளையும் கண்காணிக்கவும்',
    recent_scans: 'சமீபத்திய சோதனைகள்',
    view_all: 'அனைத்தையும் காட்டு',
    no_scans: 'இதுவரை சோதனைகள் எதுவும் பதிவு செய்யப்படவில்லை',
    start_scanning: 'இப்போதே சோதனையைத் தொடங்குங்கள்',
    total_scans: 'மொத்த சோதனைகள்',
    diseases_found: 'கண்டறியப்பட்ட நோய்கள்',
    healthy_plants: 'ஆரோக்கியமான தாவரங்கள்',
    quick_stats: 'புள்ளிவிவரங்கள்',

    // Disease Detection Page
    disease_detection_title: 'நோய் கண்டறிதல்',
    disease_detection_desc: 'நோய் கண்டறிய உங்கள் பயிரின் படத்தை பதிவேற்றவும்',
    select_crop_type: 'பயிர் வகையைத் தேர்ந்தெடுக்கவும்',
    choose_a_crop: 'பயிரைத் தேர்ந்தெடுக்கவும்',
    upload_crop_image: 'பயிர் படத்தை பதிவேற்றவும்',
    drag_drop_image: 'படத்தை இங்கே இழுத்து விடவும் (Drag & drop)',
    or: 'அல்லது',
    choose_image: 'படத்தைத் தேர்ந்தெடுக்கவும்',
    ready_for_analysis: 'படம் பகுப்பாய்விற்கு தயாராக உள்ளது',
    start_disease_scan: 'நோய் பரிசோதனையைத் தொடங்குங்கள்',
    analyzing_image: 'படம் பகுப்பாய்வு செய்யப்படுகிறது...',
    tips_title: 'சிறந்த நோய் கண்டறிதலுக்கான உதவிக்குறிப்புகள்:',
    tip1: 'பாதிக்கப்பட்ட தாவர பாகங்களின் தெளிவான, வெளிச்சமான புகைப்படங்களை எடுக்கவும்',
    tip2: 'தெரியும் அறிகுறிகளின் (புள்ளிகள், நிறமாற்றம்) நெருக்கமான புகைப்படங்களை எடுக்கவும்',
    tip3: 'பாதிக்கப்பட்ட பகுதி படத்தில் தெளிவாகத் தெரிவதை உறுதிப்படுத்திக் கொள்ளுங்கள்',
    tip4: 'சிறந்த முடிவுகளுக்கு மங்கலான அல்லது இருண்ட படங்களைத் தவிர்க்கவும்',

    // Detection Result Page
    scan_results: 'பரிசோதனை முடிவுகள்',
    crop_name: 'பயிரின் பெயர்',
    detected_disease: 'கண்டறியப்பட்ட நோய்',
    confidence_score: 'துல்லிய சதவீதம்',
    severity: 'தீவிரம்',
    scan_date: 'பரிசோதனை தேதி',
    view_recommendations: 'சிகிச்சை பரிந்துரைகளைக் காட்டு',
    healthy_desc: 'நற்செய்தி! உங்கள் பயிர் ஆரோக்கியமாகத் தெரிகிறது.',
    diagnosed_disease: 'கண்டறியப்பட்ட நோய்',

    // Treatment Page
    back_to_detection: 'மீண்டும் கண்டறிதலுக்கு',
    symptoms: 'அறிகுறிகள்',
    organic_treatment: 'இயற்கை சிகிச்சை',
    chemical_treatment: 'இரசாயன சிகிச்சை',
    recommended_dosage: 'பரிந்துரைக்கப்பட்ட அளவு',
    application_method: 'பயன்படுத்தும் முறை',
    available_in_sl: 'இலங்கையில் கிடைக்கும் பிராண்டுகள்',
    safety_precautions: 'பாதுகாப்பு முன்னெச்சரிக்கைகள்',
    prevention_tips: 'தடுப்பு குறிப்புகள்',
    quick_actions: 'உடனடி நடவடிக்கைகள்',
    scan_another_crop: 'மற்றொரு பயிரை சோதிக்கவும்',
    view_history: 'வரலாற்றைக் காட்டு',
    browse_diseases: 'நோய்களைப் பார்வையிடவும்',
    need_help: 'உதவி தேவையா?',
    help_desc: 'தனிப்பயனாக்கப்பட்ட ஆலோசனைக்கு உங்கள் உள்ளூர் விவசாய விரிவாக்க அதிகாரியைத் தொடர்பு கொள்ளவும்.',
    hotline: 'விவசாய திணைக்கள அவசர இலக்கம்: 1920',
    welcome_back_title: 'மீண்டும் வரவேற்கிறோம்',
    login_desc: 'உங்கள் பயிர்களைப் பாதுகாக்க உள்நுழையவும்',
    email_label: 'மின்னஞ்சல் (Email)',
    password_label: 'கடவுச்சொல் (Password)',
    remember_me: 'என்னை நினைவில் கொள்க',
    forgot_password: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    forgot_password_title: 'கடவுச்சொல்லை மீட்டமைக்கவும்',
    forgot_password_desc: 'கடவுச்சொல் மீட்டமைப்பு இணைப்பைப் பெற உங்கள் மின்னஞ்சலை உள்ளிடவும்.',
    reset_email_sent: 'கடவுச்சொல் மீட்டமைப்பு மின்னஞ்சல் அனுப்பப்பட்டது. உங்கள் இன்பாக்ஸைச் சரிபார்க்கவும்.',
    sending: 'அனுப்பப்படுகிறது...',
    reset_password_btn: 'மீட்டமைப்பு இணைப்பை அனுப்பு',
    back_to_login: 'உள்நுழைவுக்குத் திரும்பு',
    sign_in_btn: 'உள்நுழைக',
    signing_in: 'உள்நுழைகிறது...',
    dont_have_account: 'கணக்கு இல்லையா?',
    sign_up_link: 'பதிவு செய்க',
    agree_terms: 'உள்நுழைவதன் மூலம், எங்களது சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை நீங்கள் ஒப்புக்கொள்கிறீர்கள்',
    create_account: 'உங்கள் கணக்கை உருவாக்கவும்',
    join_farmers: 'ஆயிரக்கணக்கான இலங்கை விவசாயிகளுடன் இணையுங்கள்',
    full_name_label: 'முழு பெயர்',
    phone_label: 'கைபேசி எண் (விருப்பத்திற்குரியது)',
    district_label: 'மாவட்டம்',
    confirm_password_label: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    creating_account: 'கணக்கு உருவாக்கப்படுகிறது...',
    create_account_btn: 'கணக்கை உருவாக்கு',
    already_have_account: 'ஏற்கனவே கணக்கு உள்ளதா?',
    sign_in_link: 'உள்நுழைக',
    agree_terms_register: 'கணக்கை உருவாக்குவதன் மூலம், எங்களது சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை நீங்கள் ஒப்புக்கொள்கிறீர்கள்',
    profile_settings: 'சுயவிவர அமைப்புகள்',
    personal_info: 'தனிப்பட்ட தகவல்',
    change_password: 'கடவுச்சொல்லை மாற்றவும்',
    save_changes: 'மாற்றங்களைச் சேமிக்கவும்',
    saving_changes: 'சேமிக்கப்படுகிறது...',
    cancel_btn: 'ரத்துசெய்',
    update_password: 'கடவுச்சொல்லைப் புதுப்பிக்கவும்',
    password_security_desc: 'வலுவான, தனித்துவமான கடவுச்சொல்லைப் பயன்படுத்தி உங்கள் கணக்கைப் பாதுகாப்பாக வைத்திருங்கள்.',
    account_created_on: 'கணக்கு உருவாக்கப்பட்ட தேதி',
    scan_disease_desc: 'பயிர் நோய்களைக் கண்டறிய ஒரு படத்தைப் பதிவேற்றவும்',
    view_history_btn: 'வரலாற்றைக் காட்டு',
    view_history_desc: 'உங்களின் முந்தைய சோதனைகள் அனைத்தையும் பார்க்கவும்',
    crops_desc: 'பயிர் வகைகள் பற்றி அறியவும்',
    knowledge_base_desc: 'நோய் பற்றிய தகவல்களைப் பார்வையிடவும்',
    today: 'இன்று',
    quick_actions_title: 'உடனடி நடவடிக்கைகள்',
    weak: 'பலவீனமானது',
    medium: 'நடுத்தரமானது',
    strong: 'வலிமையானது',
    password_strength: 'கடவுச்சொல் வலிமை',
    passwords_dont_match: 'கடவுச்சொற்கள் பொருந்தவில்லை',
    password_too_short: 'கடவுச்சொல் குறைந்தது 6 எழுத்துக்களைக் கொண்டிருக்க வேண்டும்',
    select_district: 'தயவுசெய்து உங்கள் மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
    account_created: 'கணக்கு உருவாக்கப்பட்டது!',
    redirecting_login: 'உள்நுழைவு பக்கத்திற்கு திருப்பி விடப்படுகிறது...',
    select_district_placeholder: 'மாவட்டம் தேர்ந்தெடுக்கவும்',
    profile_updated_success: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    new_passwords_dont_match: 'புதிய கடவுச்சொற்கள் பொருந்தவில்லை',
    password_changed_success: 'கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது!',
    back_to_dashboard: 'மீண்டும் தகவல் பலகைக்கு',
    new_password_label: 'புதிய கடவுச்சொல்',
    confirm_new_password_label: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    search_crops: 'பயிர்களைத் தேடுங்கள்...',
    diseases_label: 'நோய்கள்',
    growing_guide_title: 'வளர்ப்பு வழிகாட்டி',
    sunlight: 'சூரிய ஒளி',
    sunlight_desc: 'தினமும் 6-8 மணிநேரம்',
    watering: 'நீர் பாய்ச்சுதல்',
    watering_desc: 'வழக்கமான, மிதமான',
    temperature: 'வெப்பநிலை',
    temperature_desc: '25-35°C உகந்தது',
    prevention_tips_avail: 'தடுப்பு குறிப்புகள் கிடைக்கின்றன',
    common_diseases: 'பொதுவான நோய்கள்',
    kb_subtitle: 'பயிர் நோய்கள், அறிகுறிகள் மற்றும் சிகிச்சைகளை பார்வையிடவும்',
    search_diseases_placeholder: 'நோய்கள் அல்லது அறிகுறிகளைத் தேடுங்கள்...',
    all_crops: 'அனைத்து பயிர்களும்',
    all_severity: 'அனைத்து தீவிரமும்',
    found: 'கண்டறியப்பட்டது',
    filters: 'வடிகட்டிகள்',
    no_diseases_found: 'நோய்கள் எதுவும் காணப்படவில்லை',
    adjust_filters: 'உங்கள் தேடல் அல்லது வடிகட்டிகளை மாற்ற முயற்சிக்கவும்',
    causes_label: 'காரணங்கள்:',
    view_treatment_btn: 'சிகிச்சையைக் காட்டு',
    need_expert_advice: 'உதவி தேவையா?',
    website_label: 'இணையதளம்:',
    hotline_label: 'அவசர எண்:',
    recommended_treatments: 'பரிந்துரைக்கப்பட்ட சிகிச்சைகள்',
    treatment_available: 'சிகிச்சை கிடைக்கிறது',
    treatment_available_desc: 'கரிம சிகிச்சைகள், இரசாயன விருப்பங்கள் மற்றும் இலங்கையில் உள்ளூரில் கிடைக்கக்கூடிய தயாரிப்புகள் உட்பட விரிவான சிகிச்சை பரிந்துரைகளைப் பெறுங்கள்.',
    detection_history: 'பரிசோதனை வரலாறு',
    detection_history_desc: 'உங்கள் ஸ்கேன் வரலாற்றைப் பார்த்து நிர்வகிக்கவும்',
    export_csv: 'CSV கோப்பாக மாற்று',
    search_history_placeholder: 'நோயின் பெயர் கொண்டு தேடுக...',
    clear_btn: 'சுத்தம் செய்க',
    no_detections_found: 'நோய் கண்டறிதல்கள் எதுவும் காணப்படவில்லை',
    adjust_filters_history: 'உங்கள் வடிகட்டிகளை மாற்ற முயற்சிக்கவும்',
    start_scanning_history: 'உங்கள் வரலாற்றைப் பார்க்க பயிர்களை ஸ்கேன் செய்யத் தொடங்குங்கள்',
    start_scanning_btn: 'ஸ்கேன் செய்யத் தொடங்குங்கள்',
    date: 'தேதி',
    actions: 'செயல்கள்',
    select_crop_alert: 'ஸ்கேன் செய்யத் தொடங்குவதற்கு முன் தயவுசெய்து மேலே உள்ள கீழ்தோன்றும் மெனுவிலிருந்து ஒரு பயிர் வகையைத் தேர்ந்தெடுக்கவும்.',
    sign_in_alert: 'பரிசோதனை முடிவுகளைச் சேமிக்க தயவுசெய்து உள்நுழையவும்.',
    process_image_error: 'படத்தை செயலாக்குவதில் தோல்வி. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    supports_formats: 'ஆதரிக்கப்படும் வடிவங்கள்: JPG, PNG, WEBP (அதிகபட்சம் 10MB)',
    good_morning: 'காலை வணக்கம்',
    good_afternoon: 'மதிய வணக்கம்',
    good_evening: 'மாலை வணக்கம்',
    email_unchangeable: 'மின்னஞ்சலை மாற்ற முடியாது',
    invalid_credentials_error: 'மின்னஞ்சல் அல்லது கடவுச்சொல் தவறானது',
  },
};

// Dictionary of translations for database dynamic content (Crops, Diseases, and Treatments)
const contentTranslations: Record<Language, Record<string, string>> = {
  en: {}, // Default fallback to English text in the DB
  si: {
    // Crop Names
    'Tomato': 'තක්කාලි',
    'Potato': 'අර්තාපල්',
    'Chilli': 'මිරිස්',
    'Rice': 'වම්බටු',
    'Cucumber': 'පිපිඤ්ඤා',

    // Disease Names
    'Early Blight': 'මුල් කොළ අංගමාරය',
    'Late Blight': 'පසු කොළ අංගමාරය',
    'Leaf Curl Virus': 'කොළ කොඩවීමේ වෛරස් රෝගය',
    'Bacterial Wilt': 'බැක්ටීරියා මැලවීම',
    'Black Scurf': 'කළු කුෂ්ඨ රෝගය',
    'Common Scab': 'පොතු කබල්ලෑ රෝගය',
    'Anthracnose': 'පලතුරු කුණුවීම (ඇන්ත්‍රැක්නෝස්)',
    'Leaf Spot': 'කොළ ලප රෝගය',
    'Powdery Mildew:': 'පිටිපුස් රෝගය',
    'Powdery Mildew': 'පිටිපුස් රෝගය',
    'Fruit and Shoot Borer': 'කරල් සහ දළු විදින පණුවා',
    'Little Leaf Disease': 'කුඩා කොළ රෝගය',
    'Verticillium Wilt': 'වර්ටිසිලියම් මැලවීම',
    'Downy Mildew': 'දියමලන් රෝගය',
    'Cucumber Mosaic Virus': 'මොසැක් වෛරස් රෝගය',
    'Healthy': 'නිරෝගී ශාකයක්',

    // Common Descriptions and guide lines
    'High': 'ඉහළ',
    'Medium': 'මධ්‍යම',
    'Low': 'පහළ',

    // Disease Symptoms
    'Dark spots with concentric rings on lower leaves, yellowing, leaf drop. Stem lesions may appear.': 'පහළ පත්‍රවල කේන්ද්‍රීය වළලු සහිත තද පැහැති ලප ඇතිවීම, කොළ කහ පැහැයට හැරීම සහ හැලීම. කඳෙහි තුවාල ඇතිවිය හැක.',
    'Water-soaked lesions that turn brown, white fungal growth on leaf undersides, fruit rot.': 'දුඹුරු පැහැයට හැරෙන තෙත් ලප ඇතිවීම, පත්‍රවල යටි පැත්තේ සුදු පැහැති දිලීර වර්ධනය සහ ගෙඩි කුණුවීම.',
    'Upward curling of leaves, yellowing, stunted growth, reduced fruit production.': 'කොළ ඉහළට රැලි වැටීම, කහ පැහැයට හැරීම, වර්ධනය බාල වීම සහ අස්වැන්න අඩුවීම.',
    'Sudden wilting, yellowing, brown staining inside stems. Plant dies within days.': 'හදිසියේම ශාකය මැලවීම, කහ පැහැයට හැරීම සහ කඳ ඇතුළත දුඹුරු පැහැ වීම. දින කිහිපයකින් ශාකය මිය යයි.',
    'Water-soaked lesions that turn brown, white fungal growth on leaf undersides, tuber rot.': 'දුඹුරු පැහැයට හැරෙන තෙත් ලප ඇතිවීම, පත්‍රවල යටි පැත්තේ සුදු පැහැති දිලීර වර්ධනය සහ අල කුණුවීම.',
    'Dark sclerotia on tuber surface, stem cankers, stunted growth.': 'අල මතුපිට තද පැහැති ලප ඇතිවීම, කඳේ තුවාල ඇතිවීම සහ වර්ධනය බාල වීම.',
    'Rough, corky lesions on tuber surface, reduced quality.': 'අල මතුපිට රළු, කොරල වැනි ලප ඇතිවීම සහ අලයේ ගුණාත්මකභාවය අඩු වීම.',
    'Sunken lesions on fruits, dark spots with orange spore masses, fruit rot.': 'ගෙඩි මතුපිට ගිලුණු ලප ඇතිවීම, තැඹිලි පැහැති බීජාණු සහිත තද ලප සහ ගෙඩි කුණුවීම.',
    'Small brown spots on leaves, yellowing, leaf drop.': 'පත්‍රවල කුඩා දුඹුරු පැහැති ලප ඇතිවීම, කහ පැහැයට හැරීම සහ කොළ හැලීම.',
    'White powdery growth on leaves and stems, yellowing, stunted growth.': 'පත්‍ර සහ කඳන් මත සුදු පැහැති පිටි වැනි වර්ධනයක් ඇතිවීම, කහ පැහැයට හැරීම සහ වර්ධනය බාල වීම.',
    'Boreholes in fruits and shoots, frass around holes, fruit decay.': 'දළු සහ ගෙඩි විද සිදුරු ඇතිවීම, සිදුරු වටා අපද්‍රව්‍ය රැඳීම සහ ගෙඩි කුණුවීම.',
    'Small leaves, excessive branching, yellowing, stunted plants.': 'කොළ ඉතා කුඩා වීම, අධික ලෙස අතු බෙදීම, කහ පැහැයට හැරීම සහ ශාකය කුරු වීම.',
    'Yellowing and wilting starting from lower leaves, brown streaks in stems.': 'පහළ කොළවලින් ආරම්භ වන කහ පැහැ වීම සහ මැලවීම, කඳේ දුඹුරු පැහැති ඉරි ඇතිවීම.',
    'Yellow angular spots on upper leaf surface, gray fungal growth underneath.': 'පත්‍රවල උඩ මතුපිට කහ පැහැති කෝණික ලප ඇතිවීම සහ යටි පැත්තේ අළු පැහැති දිලීර වර්ධනයක් ඇතිවීම.',
    'Mosaic pattern on leaves, stunted growth, deformed fruits.': 'කොළ මත ලා කහ සහ කොළ පැහැති විචිත්‍ර (මොසැක්) රටා ඇතිවීම, වර්ධනය බාල වීම සහ ගෙඩි විකෘති වීම.',

    // Prevention tips translations
    'Remove infected leaves, ensure good air circulation, avoid overhead watering, rotate crops every 2-3 years.': 'ආසාදිත කොළ ඉවත් කරන්න, හොඳ වාතාශ්‍රයක් පවත්වා ගන්න, උඩින් ජලය ඉසීමෙන් වළකින්න, වසර 2-3 කට වරක් බෝග මාරුව කරන්න.',
    'Use resistant varieties, ensure good drainage, avoid crowding plants, remove infected plants immediately.': 'ප්‍රතිරෝධී රටවල් භාවිතා කරන්න, හොඳ ජලාපවහනය සුරක්ෂිත කරන්න, පැල හරියට නොගැහෙන්නට ඉඩ දෙන්න, ආසාදිත පැල වහාම ඉවත් කරන්න.',
    'Control whitefly population, use virus-free seedlings, remove infected plants, use reflective mulches.': 'සුදුමැස්සන් පාලනය කරන්න, වෛරස් රහිත පැල භාවිතා කරන්න, ආසාදිත පැල ඉවත් කරන්න, පරාවර්තක මල්ච් භාවිතා කරන්න.',
    'Use clean tools, avoid soil waterlogging, rotate crops, remove and destroy infected plants.': 'පිරිසිදු මෙවලම් භාවිතා කරන්න, පස ජලය කඳවීමෙන් වළකින්න, බෝග මාරුව කරන්න, ආසාදිත පැල ඉවත් කර විනාශ කරන්න.',
    'Use certified seed potatoes, ensure good drainage, hill soil around plants, harvest in dry weather.': 'සහතික කළ අර්තාපල් බීජ භාවිතා කරන්න, හොඳ ජලාපවහනය සුරක්ෂිත කරන්න, පැල වටා පස ගොඩ කරන්න, වියලි කාලයේ අස්වැන්න නෙලන්න.',
    'Use certified seed potatoes, avoid planting in cold wet soil, rotate crops, improve drainage.': 'සහතික කළ අර්තාපල් බීජ භාවිතා කරන්න, සීතල හා තෙත් පසෙහි සිටුවීමෙන් වළකින්න, බෝග මාරුව කරන්න, ජලාපවහනය සාර්ථකව වැඩි දියුණු කරන්න.',
    'Maintain soil moisture during tuber formation, lower soil pH, use resistant varieties.': 'අල සෑදීමේදී පසයේ තෙතමනය පවත්වා ගන්න, පසෙහි pH අඩු කරන්න, ප්‍රතිරෝධී වර්ග භාවිතා කරන්න.',
    'Harvest fruits before fully ripe, remove infected fruits, ensure good drainage, use resistant varieties.': 'පළමුව සම්පූර්ණයෙන් පිපුණු පෙර ගෙඩි නෙලන්න, ආසාදිත ගෙඩි ඉවත් කරන්න, හොඳ ජලාපවහනය සුරක්ෂිත කරන්න, ප්‍රතිරෝධී වර්ග භාවිතා කරන්න.',
    'Remove infected leaves, avoid overhead watering, ensure good air circulation, apply copper fungicides.': 'ආසාදිත කොළ ඉවත් කරන්න, උඩින් ජලය ඉසීමෙන් වළකින්න, හොඳ වාතාශ්‍රයක් සුරක්ෂිත කරන්න, කොපර් දිලීර නාශක යොදන්න.',
    'Prune for air circulation, avoid overhead watering, apply sulfur-based fungicides, remove infected leaves.': 'වාතාශ්‍රය සඳහා කප්පාදු කරන්න, උඩින් ජලය ඉසීමෙන් වළකින්න, සල්ෆර් මත පදනම් වූ දිලීර නාශක යොදන්න, ආසාදිත කොළ ඉවත් කරන්න.',
    'Use resistant varieties, balance nitrogen fertilizer application, treat seeds before planting, avoid water stress.': 'ප්‍රතිරෝධී වර්ග භාවිතා කරන්න, නයිට්‍රජන් පොහොර සමානුපාතිකව යොදන්න, සිටුවීමට පෙර බීජ සකස් කරන්න, ජල අධික/අඩු පීඩනයෙන් වළකින්න.',
    'Maintain proper plant spacing, avoid excessive nitrogen, drain excess water, clear weeds and infected stubble.': 'නිවැරදි පැල පරතරයක් තබා ගන්න, අධික නයිට්‍රජන් වලක්වන්න, අතිරික්ත ජලය නිකුත් කරන්න, වල් පැලෑටි සහ ආසාදිත කඳුළැලි ඉවත් කරන්න.',
    'Plant resistant rice varieties, avoid over-fertilization, maintain good field drainage, treat seeds before sowing.': 'ප්‍රතිරෝධී වීනී වර්ග වගා කරන්න, අධික පොහොර යොදීමෙන් වැළකින්න, හොඳ ක්ෂේත්‍ර ජලාපවහනය තබා ගන්න, වපුරීමට පෙර බීජ සකස් කරන්න.',
    'Ensure good air circulation, avoid overhead watering, apply copper-based fungicides, remove infected leaves.': 'හොඳ වාතාශ්‍රයක් සුරක්ෂිත කරන්න, උඩින් ජලය ඉසීමෙන් වළකින්න, කොපර් මත පදනම් වූ දිලීර නාශක යොදන්න, ආසාදිත කොළ ඉවත් කරන්න.',
    'Control aphids, remove infected plants, avoid working with wet plants, use virus-free seeds.': 'කුඩිත්තන් පාලනය කරන්න, ආසාදිත පැල ඉවත් කරන්න, තෙත් පැල වලින් වැඩ කිරීමෙන් වළකින්න, වෛරස් රහිත බීජ භාවිතා කරන්න.',

    // Treatment Seed Values translations
    'Remove and burn infected lower leaves immediately. Spray Neem Seed Kernel Extract (NSKE 5%) or copper oxychloride. Ensure crop rotation with non-solanaceous crops.': 'ආසාදිත පහළ කොළ වහාම ඉවත් කර පුළුස්සා දමන්න. කොහොඹ ඇට සාරය (NSKE 5%) හෝ කොපර් ඔක්සික්ලෝරයිඩ් ඉසින්න. සොලනේසියේ නොවන බෝග සමඟ බෝග මාරුව සිදු කරන්න.',
    'Apply protective or systemic fungicides such as Mancozeb, Chlorothalonil, or Azoxystrobin.': 'මැන්කොසෙබ්, ක්ලෝරෝතැලොනිල්, හෝ ඇසොක්සිස්ට්‍රොබින් වැනි ආරක්ෂක හෝ පද්ධතිමය දිලීර නාශක යොදන්න.',
    'Mancozeb: 20-30g in 10L water; Chlorothalonil: 20g in 10L water.': 'මැන්කොසෙබ්: වතුර ලීටර් 10 කට ග්‍රෑම් 20-30; ක්ලෝරෝතැලොනිල්: වතුර ලීටර් 10 කට ග්‍රෑම් 20.',
    'Spray thoroughly on all foliage at 7-10 day intervals upon first appearance of symptoms.': 'රෝග ලක්ෂණ මුලින්ම දුටු විගස දින 7-10 ක පරතරයකින් පත්‍ර මත හොඳින් ඉසින්න.',
    'Available at local agro-chemical shops islandwide. Common brands include Dithane M-45 (Lankem), Bravo (Hayleys), and CIC Mancozeb.': 'දිවයින පුරා දේශීය කෘෂි රසායන වෙළඳසැල්වලින් ලබා ගත හැක. පොදු වෙළඳ නාම අතර Dithane M-45 (ලංකෙම්), Bravo (හේලීස්) සහ CIC මැන්කොසෙබ් ඇතුළත් වේ.',
    'Wear gloves and a protective mask during spraying. Observe a pre-harvest interval (PHI) of 7-14 days. Avoid spraying during heavy winds.': 'ඉසීමේදී අත්කවස් සහ ආරක්ෂිත මුහුණු ආවරණ පළඳින්න. අස්වැන්න නෙලා ගැනීමට දින 7-14 කට පෙර රසායන ඉසීම නවත්වන්න (PHI). තද සුළං පවතින විට ඉසීමෙන් වළකින්න.',
    
    'Ensure wide plant spacing for air circulation. Avoid overhead watering to reduce foliage wetness. Spray copper-based organic formulations on lower leaves.': 'වාතාශ්‍රය සඳහා පැල අතර පරතරය වැඩි කරන්න. පත්‍ර තෙත් වීම අඩු කිරීමට බිංදු ජල සම්පාදනය යොදාගන්න. පහළ කොළ වලට කොපර් සහිත කාබනික දියර ඉසින්න.',
    'Apply systemic combination fungicides like Metalaxyl-M + Mancozeb, Propineb, or Cymoxanil + Mancozeb.': 'මෙටලැක්සිල්-එම් + මැන්කොසෙබ්, ප්‍රොපිනෙබ් හෝ සිමොක්සනිල් + මැන්කොසෙබ් වැනි දිලීර නාශක යොදන්න.',
    'Ridomil Gold (Metalaxyl + Mancozeb): 25g in 10L water; Antracol (Propineb): 20g in 10L water.': 'රිඩොමිල් ගෝල්ඩ්: වතුර ලීටර් 10 කට ග්‍රෑම් 25; ඇන්ට්‍රකොල්: වතුර ලීටර් 10 කට ග්‍රෑම් 20.',
    'Spray immediately upon first symptom detection or when weather is cool and highly humid. Repeat at 7-day intervals in wet periods.': 'පළමු රෝග ලක්ෂණය දුටු වහාම හෝ කාලගුණය සිසිල් හා අධික ආර්ද්‍රතාවයෙන් යුක්ත වන විට ඉසින්න. වැසි සහිත කාලවලදී දින 7 ක පරතරයකින් නැවත ඉසින්න.',
    'Widely available in Sri Lankan agricultural stores. Common brands: Ridomil Gold (CIC), Antracol (Hayleys/Bayer), Lankem Mancozeb.': 'කෘෂි වෙළඳසැල්වල බහුලව තිබේ. පොදු වෙළඳ නාම: Ridomil Gold (CIC), Antracol (හේලීස්/බේයර්), ලංකෙම් මැන්කොසෙබ්.',
    'Highly toxic to aquatic life. Observe strict 14-day pre-harvest interval (PHI) for chemical options.': 'ජලජ ජීවීන්ට අතිශයින්ම විෂ සහිතයි. රසායනික ක්‍රම සඳහා අස්වැන්න නෙලීමට දින 14 කට පෙර ඉසීම නවත්වන්න (PHI).',

    'Use yellow sticky traps (10-15 traps per acre) to trap whitefly vectors. Spray neem oil (15ml per liter of water). Eradicate and burn infected plants immediately.': 'සුදුමැස්සන් අල්ලා ගැනීමට කහ ඇලෙන සුළු උගුල් (අක්කරයකට 10-15) භාවිතා කරන්න. කොහොඹ තෙල් (වතුර ලීටරයකට මිලිලීටර් 15) ඉසින්න. ආසාදිත පැල වහාම ගලවා පුළුස්සා දමන්න.',
    'Control the whitefly insect vector using systemic insecticides like Imidacloprid, Acetamiprid, or Thiamethoxam.': 'ඉමිඩක්ලෝප්‍රිඩ්, ඇසිටමිප්‍රිඩ් හෝ තියාමෙතොක්සම් වැනි කෘමිනාශක භාවිතයෙන් සුදුමැසි වාහකයා පාලනය කරන්න.',
    'Imidacloprid: 5ml in 10L water; Acetamiprid: 5g in 10L water.': 'ඉමිඩක්ලෝප්‍රිඩ්: වතුර ලීටර් 10 කට මිලිලීටර් 5; ඇසිටමිප්‍රිඩ්: වතුර ලීටර් 10 කට ග්‍රෑම් 5.',
    'Spray early in the morning or late evening targeting the undersides of the leaves where whiteflies gather.': 'සුදුමැස්සන් බහුලව ගැවසෙන කොළවල යටි පැත්ත ඉලක්ක කර උදෑසන හෝ සවස් කාලයේ ඉසින්න.',
    'Readily available at local dealers. Brands include Admire (Bayer/Hayleys), Mospilan (Lankem), and Actara (CIC).': 'දේශීය වෙළඳසැල්වලින් පහසුවෙන් ලබාගත හැක. වෙළඳ නාම අතර Admire (හේලීස්), Mospilan (ලංකෙම්) සහ Actara (CIC) ඇතුළත් වේ.',
    'Highly toxic to bees; avoid spraying during active flowering hours. Wear appropriate personal protective equipment.': 'මී මැස්සන්ට අධික ලෙස විෂ සහිත බැවින් මල් පිපෙන කාලවලදී දහවල් ඉසීමෙන් වළකින්න. සුදුසු ආරක්ෂක උපකරණ පළඳින්න.',

    'Use wild brinjal (Solanum torvum) rootstock for grafting. Soil solarization using clear polythene sheets. Practice crop rotation with paddy or maize. Apply Trichoderma-enriched compost.': 'බද්ධ කිරීම සඳහා තිත්ත තිබ්බටු (Solanum torvum) මුල් තොග භාවිතා කරන්න. විනිවිද පෙනෙන පොලිතින් භාවිතයෙන් පස සූර්ය තාපනයට ලක් කරන්න. වී හෝ බඩඉරිඟු සමඟ බෝග මාරුව සිදු කරන්න. ට්‍රයිකොඩර්මා අඩංගු කොම්පෝස්ට් යොදන්න.',
    'No effective chemical cure exists. Soil drenching with copper fungicides around healthy plants in infected fields can slow disease spread.': 'ඵලදායී රසායනික ප්‍රතිකාරයක් නොමැත. ආසාදිත වගාවල නිරෝගී පැල වටා තඹ අඩංගු දිලීර නාශක යෙදීමෙන් රෝගය පැතිරීම මන්දගාමී කළ හැක.',
    'Copper Oxychloride: 30g in 10L water.': 'කොපර් ඔක්සික්ලෝරයිඩ්: වතුර ලීටර් 10 කට ග්‍රෑම් 30.',
    'Drench the soil root zone of neighboring healthy plants. Do not spray on leaves.': 'අසල ඇති නිරෝගී ශාකවල මුල් කලාපයේ පස තෙත් කරන්න. කොළ මත ඉසින්න එපා.',
    'Copper Oxychloride is widely available. Brands: Hayleys Copper, Lankem Copper, CIC Copper Oxychloride.': 'කොපර් ඔක්සික්ලෝරයිඩ් බහුලව තිබේ. වෙළඳ නාම: Hayleys Copper, Lankem Copper, CIC Copper Oxychloride.',
    'Copper Oxychloride is widely available.': 'කොපර් ඔක්සික්ලෝරයිඩ් බහුලව තිබේ.',
    'Brands: Hayleys Copper, Lankem Copper, CIC Copper Oxychloride.': 'වෙළඳ නාම: Hayleys Copper, Lankem Copper, CIC Copper Oxychloride.',
    'Ensure pruning tools are sanitized with alcohol between plants to avoid mechanical transmission.': 'කප්පාදු කරන මෙවලම් එක් ශාකයකින් තවත් ශාකයකට යාමේදී ඇල්කොහොල් මඟින් විෂබීජහරණය කරන්න.',

    'Plant certified disease-free seed tubers. Improve soil drainage and hill up soil around plant bases. Destroy volunteer potato plants in adjacent areas.': 'සහතික කළ රෝගවලින් තොර බීජ අල සිටුවන්න. පාංශු ජලාපවහනය වැඩි දියුණු කර පැළ වටා පස් ගොඩ කරන්න. යාබද ප්‍රදේශවල ස්වේච්ඡාවෙන් වැවෙන අර්තාපල් පැල විනාශ කරන්න.',
    'Spray preventative and curative fungicides like Mancozeb, Ridomil Gold, or Fluazinam.': 'මැන්කොසෙබ්, රිඩොමිල් ගෝල්ඩ් හෝ ෆ්ලුවසිනම් වැනි දිලීර නාශක ඉසින්න.',
    'Ridomil Gold: 25g in 10L water; Mancozeb: 30g in 10L water.': 'රිඩොමිල් ගෝල්ඩ්: වතුර ලීටර් 10 කට ග්‍රෑම් 25; මැන්කොසෙබ්: වතුර ලීටර් 10 කට ග්‍රෑම් 30.',
    'Apply preventatively when weather becomes humid and cool (common in Nuwara Eliya and Badulla districts), repeating every 7-10 days.': 'කාලගුණය තෙතමනය සහිත සහ සිසිල් වන විට (නුවරඑළිය සහ බදුල්ල දිස්ත්‍රික්කවල බහුලව දක්නට ලැබේ) වැළැක්වීමේ පියවරක් ලෙස දින 7-10 කට වරක් ඉසින්න.',
    'Extremely common in upcountry agro-dealers. Distributed by CIC, Lankem, Hayleys Agriculture, and Harrisons.': 'කඳුකරයේ කෘෂි වෙළඳසැල්වල බහුලව තිබේ. CIC, ලංකෙම්, හේලීස් සහ හැරිසන්ස් සමාගම් බෙදාහරියි.',
    'Keep livestock away from treated fields. Do not exceed recommended concentrations.': 'ප්‍රතිකාර කළ කුඹුරු හෝ වගා බිම්වලින් ගවයන් ඈත් කර තබන්න. නිර්දේශිත මාත්‍රාව ඉක්මවා යන්න එපා.',

    'Rotate crops with green manures or mustard. Plant seed tubers in warm soils at shallow depths to promote fast emergence. Avoid harvesting in wet soils.': 'කොළ පොහොර හෝ අබ සමඟ බෝග මාරුව සිදු කරන්න. ඉක්මනින් පැළවීම ප්‍රවර්ධනය කිරීම සඳහා බීජ අල උණුසුම් පසෙහි නොගැඹුරු ගැඹුරකින් සිටුවන්න. තෙත් පසෙහි අස්වැන්න නෙලීමෙන් වළකින්න.',
    'Treat seed tubers with fungicides containing Pencycuron or Fludioxonil prior to planting.': 'සිටුවීමට පෙර බීජ අල පෙන්සික්‍යුරෝන් හෝ ෆ්ලුඩියොක්සොනිල් අඩංගු දිලීර නාශකවලින් සලකන්න.',
    'Monceren (Pencycuron): 1.5-2ml per liter of water for seed tuber dip.': 'Monceren (Pencycuron): බීජ අල ගිල්වීම සඳහා වතුර ලීටරයකට මිලිලීටර් 1.5-2.',
    'Dip seed tubers in the solution or spray them evenly on a clean tarp and allow to dry before planting.': 'බීජ අල ද්‍රාවණයේ ගිල්වන්න හෝ පිරිසිදු ලිනන් රෙද්දක් මත ඒකාකාරව ඉස සිටුවීමට පෙර වේලෙන්නට හරින්න.',
    'Available in potato growing regions (Nuwara Eliya, Welimada). Main distributor: CIC (Monceren).': 'අර්තාපල් වගා කරන ප්‍රදේශවල (නුවරඑළිය, වැලිමඩ) ලබා ගත හැක. ප්‍රධාන බෙදාහරින්නා: CIC (Monceren).',
    'Do not use treated seed tubers for consumption or animal feed. Wear rubber gloves during handling.': 'ප්‍රතිකාර කළ බීජ අල ආහාරයට හෝ සත්ව ආහාර සඳහා භාවිතා නොකරන්න. පරිහරණයේදී රබර් අත්කොසු පළඳින්න.',

    'Maintain high soil moisture during tuber initiation (first 4-6 weeks of growth). Incorporate sulfur to lower soil pH below 5.5. Avoid using fresh poultry manure.': 'අල සෑදෙන කාලය තුළ (වර්ධනයේ පළමු සති 4-6) පසේ ඉහළ තෙතමනයක් පවත්වා ගන්න. පසේ pH අගය 5.5 ට වඩා අඩු කිරීමට සල්ෆර් මිශ්‍ර කරන්න. නැවුම් කුකුළු පොහොර භාවිතයෙන් වළකින්න.',
    'Treat seed tubers with Mancozeb before planting to reduce seed-borne inoculum.': 'බීජ මඟින් බෝවන රෝගකාරක අවම කිරීම සඳහා සිටුවීමට පෙර බීජ අල මැන්කොසෙබ්වලින් සලකන්න.',
    'Mancozeb: 30g in 10L water for tuber wash.': 'මැන්කොසෙබ්: අල සේදීම සඳහා වතුර ලීටර් 10 කට ග්‍රෑම් 30.',
    'Wash tubers or dip them in fungicide solution before planting.': 'සිටුවීමට පෙර අල සෝදන්න හෝ දිලීර නාශක ද්‍රාවණයේ ගිල්වා ගන්න.',
    'Available islandwide via CIC, Lankem, and Hayleys Agriculture.': 'CIC, ලංකෙම් සහ හේලීස් කෘෂිකර්ම සමාගම් හරහා දිවයින පුරා ලබා ගත හැක.',
    'Dispose of wash water safely, far from natural water resources.': 'සේදුම් ජලය ස්වාභාවික ජල මූලාශ්‍රවලින් ඈත්ව ආරක්ෂිතව බැහැර කරන්න.',

    'Use pathogen-free seeds.': 'රෝගවලින් තොර බීජ භාවිතා කරන්න.',
    'Collect and destroy infected fruits and crop debris.': 'ආසාදිත ගෙඩි සහ බෝග සුන්බුන් එකතු කර විනාශ කරන්න.',
    'Ensure proper crop spacing and field drainage.': 'නිසි බෝග පරතරය සහ ජලාපවහනය තහවුරු කරන්න.',
    'Spray neem seed extract (NSKE 5%).': 'කොහොඹ ඇට සාරය (NSKE 5%) ඉසින්න.',
    'Use pathogen-free seeds. Collect and destroy infected fruits and crop debris. Ensure proper crop spacing and field drainage. Spray neem seed extract (NSKE 5%).': 'රෝගවලින් තොර බීජ භාවිතා කරන්න. ආසාදිත ගෙඩි සහ බෝග සුන්බුන් එකතු කර විනාශ කරන්න. නිසි බෝග පරතරය සහ ජලාපවහනය තහවුරු කරන්න. කොහොඹ ඇට සාරය (NSKE 5%) ඉසින්න.',
    'Spray systemic and contact fungicides like Tebuconazole + Trifloxystrobin, Carbendazim, or Mancozeb.': 'ටෙබුකොනසෝල් + ට්‍රයිෆ්ලොක්සිස්ට්‍රොබින්, කාබෙන්ඩසිම් හෝ මැන්කොසෙබ් වැනි දිලීර නාශක ඉසින්න.',
    'Nativo (Tebuconazole + Trifloxystrobin): 4g in 10L water; Mancozeb: 25g in 10L water.': 'නැටිවෝ: වතුර ලීටර් 10 කට ග්‍රෑම් 4; මැන්කොසෙබ්: වතුර ලීටර් 10 කට ග්‍රෑම් 25.',
    'Spray at 10-14 day intervals starting from the onset of flowering and fruit set.': 'මල් පිපීම සහ ගෙඩි සෑදීම ආරම්භයේ සිට දින 10-14 ක පරතරයකින් ඉසින්න.',
    'Available at agro-chemical stores. Popular brands: Nativo (Bayer/Hayleys), Lankem Carbendazim, Dithane M-45.': 'දේශීය කෘෂි රසායන වෙළඳසැල්වලින් ලබා ගත හැක. ජනප්‍රිය වෙළඳ නාම: Nativo (බේයර්/හේලීස්), Lankem Carbendazim, Dithane M-45.',
    'Available at agro-chemical stores.': 'දේශීය කෘෂි රසායන වෙළඳසැල්වලින් ලබා ගත හැක.',
    'Popular brands: Nativo (Bayer/Hayleys), Lankem Carbendazim, Dithane M-45.': 'ජනප්‍රිය වෙළඳ නාම: Nativo (බේයර්/හේලීස්), Lankem Carbendazim, Dithane M-45.',
    'Observe a pre-harvest interval (PHI) of 7 days. Avoid chemical application during peak heat.': 'අස්වැන්න නෙලීමට දින 7 කට පෙර රසායන ඉසීම නවත්වන්න (PHI). අධික උෂ්ණත්වය පවතින දහවල් කාලයේ රසායනික ද්‍රව්‍ය යෙදීමෙන් වළකින්න.',

    'Practice crop rotation. Remove weeds and wild solanaceous hosts. Avoid overhead sprinkler irrigation. Spray copper hydroxide at early stages.': 'බෝග මාරුව සිදු කරන්න. වල් පැලෑටි සහ වල් සොලනේසියේ ශාක ඉවත් කරන්න. උඩින් ජලය ඉසින ක්‍රමවලින් වළකින්න. මුල් අවධියේදී කොපර් හයිඩ්‍රොක්සයිඩ් ඉසින්න.',
    'For fungal spot: Mancozeb or Chlorothalonil. For bacterial leaf spot: Copper hydroxide mixed with Kasugamycin.': 'දිලීර ලප සඳහා: මැන්කොසෙබ් හෝ ක්ලෝරෝතැලොනිල්. බැක්ටීරියා ලප සඳහා: කොපර් හයිඩ්‍රොක්සයිඩ් සහ කසුගාමයිසින් මිශ්‍රණය.',
    'Mancozeb: 25g in 10L water; Copper Hydroxide: 20g in 10L water.': 'මැන්කොසෙබ්: වතුර ලීටර් 10 කට ග්‍රෑම් 25; කොපර් හයිඩ්‍රොක්සයිඩ්: වතුර ලීටර් 10 කට ග්‍රෑම් 20.',
    'Apply immediately when leaf spots are first observed, repeating in 10 days if rainy weather persists.': 'කොළ මත ලප මුලින්ම දුටු විගස යොදන්න, වැසි සහිත කාලගුණය පවතී නම් දින 10 කින් නැවත යොදන්න.',
    'Available at agrochemical shops. Common brands: Kocide (DuPont/CIC), Dithane M-45, Bravo.': 'දේශීය කෘෂි රසායන වෙළඳසැල්වලින් ලබා ගත හැක. පොදු වෙළඳ නාම: Kocide (CIC), Dithane M-45, Bravo.',
    'Do not spray copper fungicides during hot noon hours to prevent phytotoxicity (leaf scorch).': 'කොළ පිළිස්සීම වැළැක්වීම සඳහා උණුසුම් දහවල් කාලයේ කොපර් දිලීර නාශක ඉසීමෙන් වළකින්න.',

    'Ensure good airflow through pruning. Spray organic sulfur formulations or neem oil. Remove and destroy lower infected leaves.': 'කප්පාදු කිරීම මඟින් හොඳ වාතාශ්‍රයක් තහවුරු කරන්න. කාබනික සල්ෆර් සංයෝග හෝ කොහොඹ තෙල් ඉසින්න. පහළ ආසාදිත කොළ ඉවත් කර විනාශ කරන්න.',
    'Apply Wettable Sulfur, Hexaconazole, or Triadimefon.': 'දියවන සල්ෆර් (Wettable Sulfur), හෙක්සකොනසෝල් හෝ ට්‍රයැඩිමෆෝන් යොදන්න.',
    'Wettable Sulfur: 30-40g in 10L water; Hexaconazole: 10-15ml in 10L water.': 'දියවන සල්ෆර්: වතුර ලීටර් 10 කට ග්‍රෑම් 30-40; හෙක්සකොනසෝල්: වතුර ලීටර් 10 කට මිලිලීටර් 10-15.',
    'Spray thoroughly on both upper and lower leaf surfaces at first sign of white powdery spots.': 'සුදු පැහැති පිටි ලප මුලින්ම දුටු විගස පත්‍රයේ උඩ සහ යටි මතුපිට දෙකටම හොඳින් ඉසින්න.',
    'Available islandwide. Common brands: Sulcox (Lankem), Eraze (Hayleys), Shavit (CIC).': 'දිවයින පුරා ලබා ගත හැක. පොදු වෙළඳ නාම: Sulcox (ලංකෙම්), Eraze (හේලීස්), Shavit (CIC).',
    'Do not apply sulfur during temperatures exceeding 32 degrees C as it may cause leaf burn.': 'උෂ්ණත්වය සෙල්සියස් අංශක 32 ඉක්මවන විට සල්ෆර් යෙදීමෙන් වළකින්න, එය කොළ පිළිස්සීමට හේතු විය හැක.',

    'Weekly manual removal and destruction of wilted shoots and infected fruits. Use pheromone traps (Lucilure, 10-12 traps per acre). Spray Neem Seed Kernel Extract (NSKE 5%).': 'සතිපතා මැලවී ගිය දළු සහ ආසාදිත ගෙඩි අතින් ඉවත් කර විනාශ කරන්න. ෆෙරමෝන් උගුල් (Lucilure, අක්කරයකට 10-12) භාවිතා කරන්න. කොහොඹ ඇට සාරය (NSKE 5%) ඉසින්න.',
    'Spray systemic insecticides like Chlorantraniliprole, Spinosad, or Emamectin Benzoate.': 'ක්ලෝරන්ට්‍රැනිලිප්‍රෝල්, ස්පිනොසැඩ් හෝ එමාමෙක්ටින් බෙන්සොඒට් වැනි කෘමිනාශක ඉසින්න.',
    'Coragen (Chlorantraniliprole): 3ml in 10L water; Spinosad: 4ml in 10L water.': 'Coragen: වතුර ලීටර් 10 කට මිලිලීටර් 3; ස්පිනොසැඩ්: වතුර ලීටර් 10 කට මිලිලීටර් 4.',
    'Spray at the initiation of shoot wilting, targeting the terminal shoots and young developing fruits.': 'දළු මැලවීම ආරම්භයේදීම, අග්‍රස්ථ දළු සහ ලා වර්ධනය වන ගෙඩි ඉලක්ක කර ඉසින්න.',
    'Available at local agro-input shops. Brands: Coragen (FMC/CIC), Tracer (Dow/Hayleys).': 'දේශීය වෙළඳසැල්වලින් ලබා ගත හැක. වෙළඳ නාම: Coragen (FMC/CIC), Tracer (හේලීස්).',
    'Rotate insecticide chemical classes to prevent pest resistance. Observe a PHI of 3 days.': 'කෘමීන් ප්‍රතිරෝධී වීම වැළැක්වීම සඳහා කෘමිනාශක කාණ්ඩ මාරු කරමින් යොදන්න. PHI දින 3 කි.',

    'Pull out and burn infected plants immediately. Keep the field free of weed hosts. Use yellow sticky traps to capture leafhopper vectors.': 'ආසාදිත පැල වහාම ගලවා පුළුස්සා දමන්න. වගා බිම වල් පැලෑටි වලින් තොරව පවත්වා ගන්න. කොළ පලඟැටි වාහකයා අල්ලා ගැනීමට කහ ඇලෙන සුළු උගුල් භාවිතා කරන්න.',
    'Apply systemic insecticides to control the leafhopper vector, such as Thiamethoxam or Imidacloprid.': 'පලඟැටි වාහකයා පාලනය කිරීම සඳහා තියාමෙතොක්සම් හෝ ඉමිඩක්ලෝප්‍රිඩ් වැනි කෘමිනාශක යොදන්න.',
    'Imidacloprid: 6ml in 10L water; Thiamethoxam: 5g in 10L water.': 'ඉමිඩක්ලෝප්‍රිඩ්: වතුර ලීටර් 10 කට මිලිලීටර් 6; තියාමෙතොක්සම්: වතුර ලීටර් 10 කට ග්‍රෑම් 5.',
    'Spray early in the morning when leafhoppers are less active, targeting vegetative parts.': 'පලඟැටියන් අක්‍රීය වන උදෑසන කාලයේදී ශාකයේ පත්‍ර කොටස් ඉලක්ක කර ඉසින්න.',
    'Available islandwide. Brands: Admire (Hayleys), Actara (CIC), Lankem Imidacloprid.': 'දිවයින පුරා ලබා ගත හැක. වෙළඳ නාම: Admire (හේලීස්), Actara (CIC), ලංකෙම් ඉමිඩක්ලෝප්‍රිඩ්.',
    'Do not spray when honeybees are actively foraging to protect pollinators.': 'පරාගණ කාරකයන් ආරක්ෂා කිරීම සඳහා මී මැස්සන් සක්‍රීය වන වේලාවන්හිදී ඉසීමෙන් වළකින්න.',

    'Practice crop rotation with non-solanaceous crops for 3-4 years. Use soil solarization. Apply organic compost enriched with Trichoderma species.': 'වසර 3-4 ක් සොලනේසියේ නොවන බෝග සමඟ බෝග මාරුව සිදු කරන්න. පස සූර්ය තාපනයට ලක් කරන්න. ට්‍රයිකොඩර්මා අඩංගු කාබනික කොම්පෝස්ට් යොදන්න.',
    'No effective chemical cure exists. Drenching the soil with Carbendazim around healthy plants in infected zones can suppress soil-borne inoculum.': 'ඵලදායී රසායනික ප්‍රතිකාරයක් නොමැත. ආසාදිත කලාපවල නිරෝගී පැල වටා කාබෙන්ඩසිම් මඟින් පස තෙත් කිරීමෙන් පාංශු රෝග කාරක මර්දනය කළ හැක.',
    'Carbendazim: 15g in 10L water.': 'කාබෙන්ඩසිම්: වතුර ලීටර් 10 කට ග්‍රෑම් 15.',
    'Drench the soil surrounding adjacent healthy plants when wilted patches appear in the field.': 'වගා බිමේ මැලවුණු පැල දකින විට අසල ඇති නිරෝගී පැල වටා පස හොඳින් තෙත් කරන්න.',
    'Available at local dealers. Brands: Lankem Carbendazim, CIC Carbendazim, Hayleys Carbendazim.': 'දේශීය වෙළඳසැල්වලින් ලබා ගත හැක. වෙළඳ නාම: ලංකෙම් කාබෙන්ඩසිම්, CIC කාබෙන්ඩසිම්, හේලීස් කාබෙන්ඩසිම්.',
    'Use strictly as a soil drench. Avoid skin contact and wear protective footwear.': 'පස තෙත් කිරීමට පමණක් භාවිතා කරන්න. සම සමඟ ස්පර්ශ වීමෙන් වළකින්න සහ ආරක්ෂිත පාවහන් පළඳින්න.',

    'Provide trellis support to elevate vines and improve ventilation. Keep plant spacing wide. Avoid overhead watering. Spray copper oxychloride.': 'වැල් ඉහළට යැවීම සඳහා ආධාරක සපයා වාතාශ්‍රය වැඩි දියුණු කරන්න. පැල අතර වැඩි පරතරයක් තබන්න. උඩින් ජලය ඉසීමෙන් වළකින්න. කොපර් ඔක්සික්ලෝරයිඩ් ඉසින්න.',
    'Apply systemic combination fungicides like Metalaxyl + Mancozeb, or Propamocarb Hydrochloride.': 'මෙටලැක්සිල් + මැන්කොසෙබ් හෝ ප්‍රොපමොකාබ් හයිඩ්‍රොක්ලෝරයිඩ් වැනි දිලීර නාශක යොදන්න.',
    'Ridomil Gold (Metalaxyl + Mancozeb): 25g in 10L water.': 'රිඩොමිල් ගෝල්ඩ්: වතුර ලීටර් 10 කට ග්‍රෑම් 25.',
    'Apply weekly during cool, wet, and cloudy conditions when downy mildew spreads rapidly.': 'දියමලන් රෝගය වේගයෙන් පැතිරෙන සිසිල්, තෙත් සහ වලාකුළු සහිත කාලවලදී සතිපතා යොදන්න.',
    'Available at all agricultural stores. Brands: Ridomil Gold (CIC), Lankem Mancozeb.': 'සියලුම කෘෂි වෙළඳසැල්වල තිබේ. වෙළඳ නාම: Ridomil Gold (CIC), ලංකෙම් මැන්කොසෙබ්.',
    'Observe a pre-harvest interval (PHI) of 7 days before picking cucumbers.': 'පිපිඤ්ඤා නෙලා ගැනීමට දින 7 කට පෙර රසායන ඉසීම නවත්වන්න (PHI).',

    'Control aphid vectors using yellow sticky traps and neem oil. Eradicate and burn infected vines. Keep field borders clear of wild weed hosts.': 'කහ ඇලෙන සුළු උගුල් සහ කොහොඹ තෙල් භාවිතයෙන් කුඩිත්තන් පාලනය කරන්න. ආසාදිත වැල් ගලවා පුළුස්සා දමන්න. වගා බිම් මායිම්වල ඇති වල් පැලෑටි ඉවත් කරන්න.',
    'Control aphid populations using contact or systemic insecticides like Acetamiprid or Imidacloprid.': 'ඇසිටමිප්‍රිඩ් හෝ ඉමිඩක්ලෝප්‍රිඩ් වැනි කෘමිනාශක භාවිතයෙන් කුඩිත්තන් පාලනය කරන්න.',
    'Acetamiprid: 5g in 10L water; Imidacloprid: 5ml in 10L water.': 'ඇසිටමිප්‍රිඩ්: වතුර ලීටර් 10 කට ග්‍රෑම් 5; ඉමිඩක්ලෝප්‍රිඩ්: වතුර ලීටර් 10 කට මිලිලීටර් 5.',
    'Spray target aphid colonies under leaves. Apply in the late evening to protect pollinating bees.': 'කොළ යට ඇති කුඩිත්තන් ඉලක්ක කර ඉසින්න. පරාගණය සිදුකරන මී මැස්සන් ආරක්ෂා කිරීම සඳහා සවස් කාලයේ යොදන්න.',
    'Available at local agrochemical stores. Brands: Mospilan (Lankem), Admire (Hayleys), Actara (CIC).': 'දේශීය කෘෂි රසායන වෙළඳසැල්වලින් ලබා ගත හැක. වෙළඳ නාම: Mospilan (ලංකෙම්), Admire (හේලීස්), Actara (CIC).',
    'Cucumber plants depend heavily on bees for pollination. Avoid spraying chemicals during flowering daytime hours.': 'පිපිඤ්ඤා වගාව පරාගණය සඳහා මී මැස්සන් මත බෙහෙවින් රඳා පවතී. මල් පිපෙන දිවා කාලයේ රසායන ඉසීමෙන් වළකින්න.',
  },
  ta: {
    // Crop Names
    'Tomato': 'தக்காளி',
    'Potato': 'உருளைக்கிழங்கு',
    'Chilli': 'மிளகாய்',
    'Brinjal': 'கத்தரிக்காய்',
    'Cucumber': 'வெள்ளரிக்காய்',

    // Disease Names
    'Early Blight': 'ஆரம்ப கருகல் நோய்',
    'Late Blight': 'பிந்திய கருகல் நோய்',
    'Leaf Curl Virus': 'இலை சுருட்டல் வைரஸ் நோய்',
    'Bacterial Wilt': 'பாக்டீரியா வாடல் நோய்',
    'Black Scurf': 'கருப்பு செதில் நோய்',
    'Common Scab': 'சாதாரண சொறி நோய்',
    'Anthracnose': 'கனி அழுகல் (அன்த்ராக்னஸ்)',
    'Leaf Spot': 'இலைப்புள்ளி நோய்',
    'Powdery Mildew': 'சாம்பல் நோய்',
    'Fruit and Shoot Borer': 'காய் மற்றும் தண்டு துளைப்பான்',
    'Little Leaf Disease': 'சிறு இலை நோய்',
    'Verticillium Wilt': 'வெர்டிசிலியம் வாடல் நோய்',
    'Downy Mildew': 'அடிச்சாம்பல் நோய்',
    'Cucumber Mosaic Virus': 'வெள்ளரி மொசைக் வைரஸ்',
    'Healthy': 'ஆரோக்கியமான தாவரம்',

    // Common Descriptions and guide lines
    'High': 'அதிகம்',
    'Medium': 'நடுத்தரம்',
    'Low': 'குறைவு',

    // Disease Symptoms
    'Dark spots with concentric rings on lower leaves, yellowing, leaf drop. Stem lesions may appear.': 'கீழ் இலைகளில் வளைய வடிவிலான இருண்ட புள்ளிகள் தோன்றுதல், இலைகள் மஞ்சள் நிறமாகி உதிர்தல். தண்டிலும் புண்கள் ஏற்படலாம்.',
    'Water-soaked lesions that turn brown, white fungal growth on leaf undersides, fruit rot.': 'நீர் வடிந்த தழும்புகள் பழுப்பு நிறமாக மாறுதல், இலையின் அடியில் வெள்ளை பூஞ்சை வளர்தல் மற்றும் காய் அழுகல்.',
    'Upward curling of leaves, yellowing, stunted growth, reduced fruit production.': 'இலைகள் மேல்நோக்கிச் சுருங்குதல், மஞ்சள் நிறமாதல், வளர்ச்சி குன்றுதல் மற்றும் காய் உற்பத்தி குறைதல்.',
    'Sudden wilting, yellowing, brown staining inside stems. Plant dies within days.': 'திடீரென வாடுதல், மஞ்சள் நிறமாதல் மற்றும் தண்டின் உட்பகுதி பழுப்பு நிறமாதல். சில நாட்களில் தாவரம் மடிந்துவிடும்.',
    'Water-soaked lesions that turn brown, white fungal growth on leaf undersides, tuber rot.': 'நீர் வடிந்த தழும்புகள் பழுப்பு நிறமாக மாறுதல், இலையின் அடியில் வெள்ளை பூஞ்சை வளர்தல் மற்றும் கிழங்கு அழுகல்.',
    'Dark sclerotia on tuber surface, stem cankers, stunted growth.': 'கிழங்கின் மேற்பரப்பில் இருண்ட தழும்புகள் தோன்றுதல், தண்டு புண்கள் மற்றும் வளர்ச்சி குன்றுதல்.',
    'Rough, corky lesions on tuber surface, reduced quality.': 'கிழங்கின் மேற்பரப்பில் சொரசொரப்பான சொறி போன்ற தழும்புகள் தோன்றுதல் மற்றும் தரம் குறைதல்.',
    'Sunken lesions on fruits, dark spots with orange spore masses, fruit rot.': 'காய்களில் பள்ளமான புண்கள், ஆரஞ்சு நிற வித்துக்களுடன் கூடிய கரும்புள்ளிகள் மற்றும் காய் அழுகல்.',
    'Small brown spots on leaves, yellowing, leaf drop.': 'இலைகளில் சிறிய பழுப்பு நிற புள்ளிகள் தோன்றுதல், மஞ்சள் நிறமாதல் மற்றும் இலைகள் உதிர்தல்.',
    'White powdery growth on leaves and stems, yellowing, stunted growth.': 'இலைகள் மற்றும் தண்டுகளில் வெள்ளை நிற மாவு போன்ற பூஞ்சை வளர்தல், மஞ்சள் நிறமாதல் மற்றும் வளர்ச்சி குன்றுதல்.',
    'Boreholes in fruits and shoots, frass around holes, fruit decay.': 'தண்டு மற்றும் காய்களில் துளைகள் ஏற்படுதல், துளைகளைச் சுற்றி கழிவுகள் காணப்படல் மற்றும் காய் அழுகல்.',
    'Small leaves, excessive branching, yellowing, stunted plants.': 'இலைகள் மிகச் சிறியதாக மாறுதல், அதிகப்படியான கிளைகள் தோன்றுதல், மஞ்சள் நிறமாதல் மற்றும் தாவரம் குள்ளமாதல்.',
    'Yellowing and wilting starting from lower leaves, brown streaks in stems.': 'கீழ் இலைகளில் இருந்து தொடங்கும் மஞ்சள் நிறமாதல் மற்றும் வாடல், தண்டுகளில் பழுப்பு நிற கோடுகள் ஏற்படுதல்.',
    'Yellow angular spots on upper leaf surface, gray fungal growth underneath.': 'இலைகளின் மேல் பகுதியில் மஞ்சள் நிற கோண புள்ளிகள் தோன்றுதல் மற்றும் இலையின் அடியில் சாம்பல் நிற பூஞ்சை வளர்தல்.',
    'Mosaic pattern on leaves, stunted growth, deformed fruits.': 'இலைகளில் மஞ்சள் மற்றும் பச்சை நிற மொசைக் புள்ளிகள் தோன்றுதல், வளர்ச்சி குன்றுதல் மற்றும் காய்கள் சிதைவடைதல்.',

    // Prevention tips translations
    'Remove infected leaves, ensure good air circulation, avoid overhead watering, rotate crops every 2-3 years.': 'பாதிக்கப்பட்ட இலைகளை அகற்றி, நல்ல காற்றோட்டத்தை பராமரித்து, மேலிருந்து நீர் தெளிப்பதைத் தவிர்த்து, 2-3 ஆண்டுகளுக்கு ஒருமுறை பயிர் சுழற்சியை மேற்கொள்ளுங்கள்.',
    'Use resistant varieties, ensure good drainage, avoid crowding plants, remove infected plants immediately.': 'எதிர்ப்பு வகைகளைப் பயன்படுத்துங்கள், நல்ல வடிகால் வசதியை உறுதி செய்யுங்கள், செடிகளை அடர்த்தியாக வைப்பதைத் தவிர்க்கவும், பாதிக்கப்பட்ட செடிகளை உடனடியாக அகற்றவும்.',
    'Control whitefly population, use virus-free seedlings, remove infected plants, use reflective mulches.': 'வெள்ளை ஈக்களை கட்டுப்படுத்துங்கள், வைரஸ் இல்லாத நாற்றுகளைப் பயன்படுத்துங்கள், பாதிக்கப்பட்ட செடிகளை அகற்றுங்கள், பிரதிபலிக்கும் மேல்புற பூச்சுகளைப் பயன்படுத்துங்கள்.',
    'Use clean tools, avoid soil waterlogging, rotate crops, remove and destroy infected plants.': 'சுத்தமான கருவிகளைப் பயன்படுத்துங்கள், மண்ணில் நீர் தேங்குவதைத் தவிர்க்கவும், பயிர் சுழற்சியை மேற்கொள்ளுங்கள், பாதிக்கப்பட்ட செடிகளை அகற்றி அழிக்கவும்.',
    'Use certified seed potatoes, ensure good drainage, hill soil around plants, harvest in dry weather.': 'சான்றளிக்கப்பட்ட விதை உருளைக்கிழங்குகளைப் பயன்படுத்துங்கள், நல்ல வடிகாலைக் கொண்டிருங்கள், செடிகளின் சுற்றிலும் மண்ணை மடக்கி, வறண்ட காலத்தில் அறுவடை செய்யுங்கள்.',
    'Use certified seed potatoes, avoid planting in cold wet soil, rotate crops, improve drainage.': 'சான்றளிக்கப்பட்ட விதை உருளைக்கிழங்குகளைப் பயன்படுத்துங்கள், குளிர்ந்த ஈரமான மண்ணில் நடுவதைக் தவிர்க்கவும், பயிர் சுழற்சியை மேற்கொள்ளுங்கள், வடிகால்களை மேம்படுத்துங்கள்.',
    'Maintain soil moisture during tuber formation, lower soil pH, use resistant varieties.': 'கிழங்கு உருவாகும் காலத்தில் மண்ணின் ஈரப்பதத்தை பராமரியுங்கள், மண்ணின் pH ஐ குறைக்கவும், எதிர்ப்பு வகைகளைப் பயன்படுத்துங்கள்.',
    'Harvest fruits before fully ripe, remove infected fruits, ensure good drainage, use resistant varieties.': 'முழுமையாக பழுக்குமுன் காய்களை அறுவடை செய்யுங்கள், பாதிக்கப்பட்ட காய்களை அகற்றுங்கள், நல்ல வடிகாலைக் காப்பாற்றுங்கள், எதிர்ப்பு வகைகளைப் பயன்படுத்துங்கள்.',
    'Remove infected leaves, avoid overhead watering, ensure good air circulation, apply copper fungicides.': 'பாதிக்கப்பட்ட இலைகளை அகற்றுங்கள், மேலிருந்து நீர் தெளிப்பதைத் தவிர்க்கவும், நல்ல காற்றோட்டத்தை உறுதிசெய்யவும், செம்பு பூஞ்சைக் கொல்லிகளைப் பயன்படுத்துங்கள்.',
    'Prune for air circulation, avoid overhead watering, apply sulfur-based fungicides, remove infected leaves.': 'காற்றோட்டத்திற்காக கத்தரிக்கவும், மேலிருந்து நீர் தெளிப்பதைத் தவிர்க்கவும், கந்தக அடிப்படையிலான பூஞ்சைக் கொல்லிகளைப் பயன்படுத்தவும், பாதிக்கப்பட்ட இலைகளை அகற்றவும்.',
    'Use resistant varieties, balance nitrogen fertilizer application, treat seeds before planting, avoid water stress.': 'எதிர்ப்பு வகைகளைப் பயன்படுத்துங்கள், நைட்ரஜன் உரத்தை சமநிலையில் பயன்படுத்துங்கள், நடவு செய்வதற்கு முன் விதைகளைச் சிகிச்சையுங்கள், நீர் அழுத்தத்தைத் தவிர்க்கவும்.',
    'Maintain proper plant spacing, avoid excessive nitrogen, drain excess water, clear weeds and infected stubble.': 'சரியான செடி இடைவெளியை பராமரிக்கவும், அதிக நைட்ரஜனைத் தவிர்க்கவும், அதிகப்படியான நீரை வெளியேற்றவும், களைகளையும் பாதிக்கப்பட்ட எச்சங்களையும் அகற்றவும்.',
    'Plant resistant rice varieties, avoid over-fertilization, maintain good field drainage, treat seeds before sowing.': 'எதிர்ப்பு நெல் வகைகளை நடவு செய்யுங்கள், அதிக உரம் இடுவதைத் தவிர்க்கவும், நல்ல வயல் வடிகாலைப் பராமரிக்கவும், விதைகளை விதைப்பதற்கு முன் சிகிச்சையுங்கள்.',
    'Ensure good air circulation, avoid overhead watering, apply copper-based fungicides, remove infected leaves.': 'நல்ல காற்றோட்டத்தை உறுதி செய்யுங்கள், மேலிருந்து நீர் தெளிப்பதைத் தவிர்க்கவும், செம்பு அடிப்படையிலான பூஞ்சைக் கொல்லிகளைப் பயன்படுத்துங்கள், பாதிக்கப்பட்ட இலைகளை அகற்றவும்.',
    'Control aphids, remove infected plants, avoid working with wet plants, use virus-free seeds.': 'அசுவினிகளை கட்டுப்படுத்துங்கள், பாதிக்கப்பட்ட செடிகளை அகற்றுங்கள், ஈரமான செடிகளுடன் வேலை செய்வதைத் தவிர்க்கவும், வைரஸ் இல்லாத விதைகளைப் பயன்படுத்துங்கள்.',

    // Treatment Seed Values translations in Tamil
    'Remove and burn infected lower leaves immediately. Spray Neem Seed Kernel Extract (NSKE 5%) or copper oxychloride. Ensure crop rotation with non-solanaceous crops.': 'பாதிக்கப்பட்ட கீழ் இலைகளை உடனடியாக அகற்றி எரிக்கவும். வேப்பம்பருப்பு சாறு (NSKE 5%) அல்லது செம்பு ஒக்சி குளோரைடு தெளிக்கவும். மாற்றுப் பயிர் சுழற்சியை மேற்கொள்ளவும்.',
    'Apply protective or systemic fungicides such as Mancozeb, Chlorothalonil, or Azoxystrobin.': 'மேன்கோசெப், குளோரோதலோனில் போன்ற பூஞ்சைக் கொல்லிகளைப் பயன்படுத்தவும்.',
    'Mancozeb: 20-30g in 10L water; Chlorothalonil: 20g in 10L water.': 'மேன்கோசெப்: 10 லீட்டர் நீருக்கு 20-30 கிராம்; குளோரோதலோனில்: 10 லீட்டர் நீருக்கு 20 கிராம்.',
    'Spray thoroughly on all foliage at 7-10 day intervals upon first appearance of symptoms.': 'அறிகுறிகள் முதலில் தென்பட்டவுடன் 7-10 நாட்கள் இடைவெளியில் இலைகளில் நன்றாகத் தெளிக்கவும்.',
    'Available at local agro-chemical shops islandwide. Common brands include Dithane M-45 (Lankem), Bravo (Hayleys), and CIC Mancozeb.': 'நாடு முழுவதும் உள்ள விவசாய கடைகளில் கிடைக்கும். பொதுவான பிராண்டுகள்: Dithane M-45 (Lankem), Bravo (Hayleys), CIC Mancozeb.',
    'Wear gloves and a protective mask during spraying. Observe a pre-harvest interval (PHI) of 7-14 days. Avoid spraying during heavy winds.': 'தெளிக்கும் போது கையுறைகள் மற்றும் முகமூடி அணியுங்கள். அறுவடைக்கு 7-14 நாட்களுக்கு முன்பு தெளிப்பதை நிறுத்துங்கள் (PHI). பலத்த காற்றின் போது தெளிப்பதைத் தவிர்க்கவும்.',

    'Ensure wide plant spacing for air circulation. Avoid overhead watering to reduce foliage wetness. Spray copper-based organic formulations on lower leaves.': 'காற்றோட்டத்திற்காக செடிகளுக்கு இடையில் அதிக இடைவெளியை விடுங்கள். சொட்டு நீர் பாசன முறையைப் பயன்படுத்தவும். கீழ் இலைகளில் செம்பு கலந்த கரிம திரவங்களைத் தெளிக்கவும்.',
    'Apply systemic combination fungicides like Metalaxyl-M + Mancozeb, Propineb, or Cymoxanil + Mancozeb.': 'மெட்டாலக்சில்-எம் + மேன்கோசெப் போன்ற பூஞ்சைக் கொல்லிகளைப் பயன்படுத்தவும்.',
    'Ridomil Gold (Metalaxyl + Mancozeb): 25g in 10L water; Antracol (Propineb): 20g in 10L water.': 'ரிடோமில் கோல்ட்: 10 லீட்டர் நீருக்கு 25 கிராம்; அன்ட்ராகோல்: 10 லீட்டர் நீருக்கு 20 கிராம்.',
    'Spray immediately upon first symptom detection or when weather is cool and highly humid. Repeat at 7-day intervals in wet periods.': 'அறிகுறிகள் தென்பட்டவுடன் அல்லது வானிலை குளிர்ச்சியாக இருக்கும்போது தெளிக்கவும். மழைக்காலத்தில் 7 நாட்கள் இடைவெளியில் மீண்டும் தெளிக்கவும்.',
    'Widely available in Sri Lankan agricultural stores. Common brands: Ridomil Gold (CIC), Antracol (Hayleys/Bayer), Lankem Mancozeb.': 'விவசாய கடைகளில் பரவலாகக் கிடைக்கும். பொதுவான பிராண்டுகள்: Ridomil Gold (CIC), Antracol (Hayleys/Bayer).',
    'Highly toxic to aquatic life. Observe strict 14-day pre-harvest interval (PHI) for chemical options.': 'நீர்வாழ் உயிரினங்களுக்கு மிகவும் நச்சுத்தன்மை வாய்ந்தது. அறுவடைக்கு 14 நாட்களுக்கு முன்பு தெளிப்பதை நிறுத்துங்கள் (PHI).',

    'Use yellow sticky traps (10-15 traps per acre) to trap whitefly vectors. Spray neem oil (15ml per liter of water). Eradicate and burn infected plants immediately.': 'வெள்ளைப் ஈக்களைப் பிடிக்க மஞ்சள் ஒட்டும் பொறிகளைப் (ஏக்கருக்கு 10-15) பயன்படுத்தவும். வேப்பெண்ணெய் (ஒரு லீட்டர் நீருக்கு 15 மில்லி) தெளிக்கவும். பாதிக்கப்பட்ட செடிகளை அகற்றி எரிக்கவும்.',
    'Control the whitefly insect vector using systemic insecticides like Imidacloprid, Acetamiprid, or Thiamethoxam.': 'இமிடா குளோபிரிட் போன்ற பூச்சிக்கொல்லிகளைப் பயன்படுத்தி வெள்ளை ஈக்களைக் கட்டுப்படுத்தவும்.',
    'Imidacloprid: 5ml in 10L water; Acetamiprid: 5g in 10L water.': 'இமிடா குளோபிரிட்: 10 லீட்டர் நீருக்கு 5 மில்லி; அசிடாமிபிரிட்: 10 லீட்டர் நீருக்கு 5 கிராம்.',
    'Spray early in the morning or late evening targeting the undersides of the leaves where whiteflies gather.': 'வெள்ளை ஈக்கள் கூடும் இலைகளின் அடிப்பகுதியை இலக்காகக் கொண்டு அதிகாலை அல்லது மாலை வேளையில் தெளிக்கவும்.',
    'Readily available at local dealers. Brands include Admire (Bayer/Hayleys), Mospilan (Lankem), and Actara (CIC).': 'உள்ளூர் விவசாய கடைகளில் கிடைக்கும். பிராண்டுகள்: Admire (Hayleys), Mospilan (Lankem), Actara (CIC).',
    'Highly toxic to bees; avoid spraying during active flowering hours. Wear appropriate personal protective equipment.': 'தேனீக்களுக்கு மிகவும் நச்சுத்தன்மை வாய்ந்தது; பூக்கும் நேரத்தில் தெளிப்பதைத் தவிர்க்கவும். பாதுகாப்பு உபகரணங்களை அணியுங்கள்.',

    'Use wild brinjal (Solanum torvum) rootstock for grafting. Soil solarization using clear polythene sheets. Practice crop rotation with paddy or maize. Apply Trichoderma-enriched compost.': 'ஒட்டு கட்டுவதற்கு காட்டு கத்தரி (Solanum torvum) வேர்களைப் பயன்படுத்தவும். சூரிய ஒளியைப் பயன்படுத்தி மண்ணைச் சூடாக்கவும். நெல் அல்லது சோளத்துடன் பயிர் சுழற்சி செய்யுங்கள். டிரைக்கோடெர்மா கலந்த உரம் இடவும்.',
    'No effective chemical cure exists. Soil drenching with copper fungicides around healthy plants in infected fields can slow disease spread.': 'பயனுள்ள இரசாயன சிகிச்சை எதுவும் இல்லை. பாதிக்கப்பட்ட வயலில் உள்ள ஆரோக்கியமான செடிகளைச் சுற்றி செம்பு பூஞ்சைக் கொல்லிகளை ஊற்றுவதன் மூலம் பரவலைத் தடுக்கலாம்.',
    'Copper Oxychloride: 30g in 10L water.': 'செம்பு ஒக்சி குளோரைடு: 10 லீட்டர் நீருக்கு 30 கிராம்.',
    'Drench the soil root zone of neighboring healthy plants. Do not spray on leaves.': 'அருகிலுள்ள ஆரோக்கியமான செடிகளின் வேர்ப் பகுதியில் மண்ணை நனைக்கவும். இலைகளில் தெளிக்க வேண்டாம்.',
    'Copper Oxychloride is widely available. Brands: Hayleys Copper, Lankem Copper, CIC Copper Oxychloride.': 'செம்பு ஒக்சி குளோரைடு பரவலாகக் கிடைக்கும். பிராண்டுகள்: Hayleys Copper, Lankem Copper, CIC Copper Oxychloride.',
    'Copper Oxychloride is widely available.': 'செம்பு ஒக்சி குளோரைடு பரவலாகக் கிடைக்கும்.',
    'Brands: Hayleys Copper, Lankem Copper, CIC Copper Oxychloride.': 'பிராண்டுகள்: Hayleys Copper, Lankem Copper, CIC Copper Oxychloride.',
    'Ensure pruning tools are sanitized with alcohol between plants to avoid mechanical transmission.': 'செடிகளை கத்தரிக்கும் கருவிகளை ஒரு செடியிலிருந்து அடுத்த செடிக்கு மாற்றும்போது மதுசாரத்தால் சுத்தப்படுத்தவும்.',

    'Plant certified disease-free seed tubers. Improve soil drainage and hill up soil around plant bases. Destroy volunteer potato plants in adjacent areas.': 'நோயற்ற சான்றளிக்கப்பட்ட விதை கிழங்குகளை நடுங்கள். வடிகால் வசதியை மேம்படுத்தி செடியைச் சுற்றி மண்ணை அணைக்கவும். அருகிலுள்ள காட்டு உருளைக்கிழங்கு செடிகளை அழிக்கவும்.',
    'Spray preventative and curative fungicides like Mancozeb, Ridomil Gold, or Fluazinam.': 'மேன்கோசெப், ரிடோமில் கோல்ட் போன்ற பூஞ்சைக் கொல்லிகளைத் தெளிக்கவும்.',
    'Ridomil Gold: 25g in 10L water; Mancozeb: 30g in 10L water.': 'ரிடோமில் கோல்ட்: 10 லீட்டர் நீருக்கு 25 கிராம்; மேன்கோசெப்: 10 லீட்டர் நீருக்கு 30 கிராம்.',
    'Apply preventatively when weather becomes humid and cool (common in Nuwara Eliya and Badulla districts), repeating every 7-10 days.': 'வானிலை குளிர்ச்சியாக இருக்கும்போது (நுவரெலியா, பதுளை) முன்னெச்சரிக்கையாக 7-10 நாட்களுக்கு ஒருமுறை தெளிக்கவும்.',
    'Extremely common in upcountry agro-dealers. Distributed by CIC, Lankem, Hayleys Agriculture, and Harrisons.': 'மலைநாட்டு விவசாய கடைகளில் பரவலாகக் கிடைக்கும். CIC, Lankem, Hayleys ஆகியவற்றால் விநியோகிக்கப்படுகிறது.',
    'Keep livestock away from treated fields. Do not exceed recommended concentrations.': 'விவசாய நிலங்களில் இருந்து கால்நடைகளைத் தள்ளி வைக்கவும். பரிந்துரைக்கப்பட்ட அளவைத் தாண்ட வேண்டாம்.',

    'Rotate crops with green manures or mustard. Plant seed tubers in warm soils at shallow depths to promote fast emergence. Avoid harvesting in wet soils.': 'பசுந்தாள் உரம் அல்லது கடுகைக் கொண்டு பயிர் சுழற்சி செய்யுங்கள். கிழங்குகளை மிதமான மண்ணில் குறைந்த ஆழத்தில் நடுங்கள். ஈரமான மண்ணில் அறுவடை செய்வதைத் தவிர்க்கவும்.',
    'Treat seed tubers with fungicides containing Pencycuron or Fludioxonil prior to planting.': 'நடவு செய்வதற்கு முன் விதை கிழங்குகளை பென்சிகுரான் போன்ற பூஞ்சைக் கொல்லிகளால் சுத்திகரிக்கவும்.',
    'Monceren (Pencycuron): 1.5-2ml per liter of water for seed tuber dip.': 'Monceren (Pencycuron): கிழங்குகளை நனைக்க ஒரு லீட்டர் நீருக்கு 1.5-2 மில்லி.',
    'Dip seed tubers in the solution or spray them evenly on a clean tarp and allow to dry before planting.': 'விதை கிழங்குகளை கரைசலில் நனைக்கவும் அல்லது தெளித்து நடவு செய்வதற்கு முன் உலர வைக்கவும்.',
    'Available in potato growing regions (Nuwara Eliya, Welimada). Main distributor: CIC (Monceren).': 'உருளைக்கிழங்கு வளரும் பகுதிகளில் (நுவரெலியா, வெலிமடை) கிடைக்கும். விநியோகஸ்தர்: CIC (Monceren).',
    'Do not use treated seed tubers for consumption or animal feed. Wear rubber gloves during handling.': 'சிகிச்சை அளிக்கப்பட்ட விதை கிழங்குகளை உண்ணவோ விலங்குகளுக்கு உணவாகவோ பயன்படுத்த வேண்டாம். கையுறைகளை அணியுங்கள்.',

    'Maintain high soil moisture during tuber initiation (first 4-6 weeks of growth). Incorporate sulfur to lower soil pH below 5.5. Avoid using fresh poultry manure.': 'கிழங்கு உருவாகும் காலத்தில் (முதல் 4-6 வாரங்கள்) மண்ணின் ஈரப்பதத்தை அதிகமாக பராமரிக்கவும். மண்ணின் pH ஐ குறைக்க கந்தகம் இடவும். புதிய கோழி எருவை தவிர்க்கவும்.',
    'Treat seed tubers with Mancozeb before planting to reduce seed-borne inoculum.': 'விதையினால் பரவும் நோய்களைக் குறைக்க நடுவதற்கு முன் விதை கிழங்குகளை மேன்கோசெப் மூலம் சுத்திகரிக்கவும்.',
    'Mancozeb: 30g in 10L water for tuber wash.': 'மேன்கோசெப்: கிழங்குகளைக் கழுவ 10 லீட்டர் நீருக்கு 30 கிராம்.',
    'Wash tubers or dip them in fungicide solution before planting.': 'நடுவதற்கு முன் கிழங்குகளைக் கழுவவும் அல்லது பூஞ்சைக் கொல்லி கரைசலில் நனைக்கவும்.',
    'Available islandwide via CIC, Lankem, and Hayleys Agriculture.': 'நாடு முழுவதும் CIC, Lankem மற்றும் Hayleys விவசாய நிறுவனங்கள் மூலம் கிடைக்கும்.',
    'Dispose of wash water safely, far from natural water resources.': 'கழுவிய நீரை இயற்கை நீர்நிலைகளில் இருந்து தள்ளி பாதுகாப்பாக அகற்றவும்.',

    'Use pathogen-free seeds.': 'நோயற்ற விதைகளைப் பயன்படுத்துங்கள்.',
    'Collect and destroy infected fruits and crop debris.': 'பாதிக்கப்பட்ட காய்கள் மற்றும் கழிவுகளை அகற்றி அழிக்கவும்.',
    'Ensure proper crop spacing and field drainage.': 'போதிய வடிகால் வசதியை உறுதி செய்யவும்.',
    'Spray neem seed extract (NSKE 5%).': 'வேப்பம்பருப்பு சாறு தெளிக்கவும்.',
    'Use pathogen-free seeds. Collect and destroy infected fruits and crop debris. Ensure proper crop spacing and field drainage. Spray neem seed extract (NSKE 5%).': 'நோயற்ற விதைகளைப் பயன்படுத்துங்கள். பாதிக்கப்பட்ட காய்கள் மற்றும் கழிவுகளை அகற்றி அழிக்கவும். போதிய வடிகால் வசதியை உறுதி செய்யவும். வேப்பம்பருப்பு சாறு தெளிக்கவும்.',
    'Spray systemic and contact fungicides like Tebuconazole + Trifloxystrobin, Carbendazim, or Mancozeb.': 'டெபுகோனசோல் போன்ற பூஞ்சைக் கொல்லிகளைத் தெளிக்கவும்.',
    'Nativo (Tebuconazole + Trifloxystrobin): 4g in 10L water; Mancozeb: 25g in 10L water.': 'நாட்டிவோ: 10 லீட்டர் நீருக்கு 4 கிராம்; மேன்கோசெப்: 10 லீட்டர் நீருக்கு 25 கிராம்.',
    'Spray at 10-14 day intervals starting from the onset of flowering and fruit set.': 'பூக்கத் தொடங்கும் காலத்தில் இருந்து 10-14 நாட்கள் இடைவெளியில் தெளிக்கவும்.',
    'Available at agro-chemical stores. Popular brands: Nativo (Bayer/Hayleys), Lankem Carbendazim, Dithane M-45.': 'விவசாய கடைகளில் கிடைக்கும். பிரபலமான பிராண்டுகள்: Nativo (Bayer/Hayleys), லங்கேம் கார்பென்டாசிம், Dithane M-45.',
    'Available at agro-chemical stores.': 'விவசாய கடைகளில் கிடைக்கும்.',
    'Popular brands: Nativo (Bayer/Hayleys), Lankem Carbendazim, Dithane M-45.': 'பிரபலமான பிராண்டுகள்: Nativo (Bayer/Hayleys), லங்கேம் கார்பென்டாசிம், Dithane M-45.',
    'Observe a pre-harvest interval (PHI) of 7 days. Avoid chemical application during peak heat.': 'அறுவடைக்கு 7 நாட்களுக்கு முன்பு தெளிப்பதை நிறுத்துங்கள் (PHI). அதிக வெயில் உள்ள மதிய நேரங்களில் தெளிப்பதைத் தவிர்க்கவும்.',

    'Practice crop rotation. Remove weeds and wild solanaceous hosts. Avoid overhead sprinkler irrigation. Spray copper hydroxide at early stages.': 'பயிர் சுழற்சியை மேற்கொள்ளவும். களைகளை அகற்றவும். இலைகளின் மேல் நீர் தெளிக்கும் முறைகளைத் தவிர்க்கவும். ஆரம்ப கட்டங்களில் செம்பு ஹைட்ராக்சைடு தெளிக்கவும்.',
    'For fungal spot: Mancozeb or Chlorothalonil. For bacterial leaf spot: Copper hydroxide mixed with Kasugamycin.': 'பூஞ்சை புள்ளிகளுக்கு: மேன்கோசெப். பாக்டீரியா புள்ளிகளுக்கு: செம்பு ஹைட்ராக்சைடு மற்றும் காசுகாமைசின் கலவை.',
    'Mancozeb: 25g in 10L water; Copper Hydroxide: 20g in 10L water.': 'மேன்கோசெப்: 10 லீட்டர் நீருக்கு 25 கிராம்; செம்பு ஹைட்ராக்சைடு: 10 லீட்டர் நீருக்கு 20 கிராம்.',
    'Apply immediately when leaf spots are first observed, repeating in 10 days if rainy weather persists.': 'இலைகளில் புள்ளிகள் கண்டறியப்பட்டவுடன் தெளிக்கவும், மழை நீடித்தால் 10 நாட்களில் மீண்டும் தெளிக்கவும்.',
    'Available at agrochemical shops. Common brands: Kocide (DuPont/CIC), Dithane M-45, Bravo.': 'விவசாய கடைகளில் கிடைக்கும். பொதுவான பிராண்டுகள்: Kocide (CIC), Dithane M-45, Bravo.',
    'Do not spray copper fungicides during hot noon hours to prevent phytotoxicity (leaf scorch).': 'இலைகள் கருகாமல் இருக்க வெயில் அதிகமான மதிய நேரங்களில் செம்பு பூஞ்சைக் கொல்லிகளைத் தெளிப்பதைத் தவிர்க்கவும்.',

    'Ensure good airflow through pruning. Spray organic sulfur formulations or neem oil. Remove and destroy lower infected leaves.': 'கத்தரிப்பதன் மூலம் நல்ல காற்றோட்டத்தை உறுதி செய்யவும். கந்தக கலவைகள் அல்லது வேப்ப எண்ணெய் தெளிக்கவும். பாதிக்கப்பட்ட கீழ் இலைகளை அழிக்கவும்.',
    'Apply Wettable Sulfur, Hexaconazole, or Triadimefon.': 'கந்தக பவுடர் (Wettable Sulfur) அல்லது ஹெக்சா கோனசோல் பயன்படுத்தவும்.',
    'Wettable Sulfur: 30-40g in 10L water; Hexaconazole: 10-15ml in 10L water.': 'கந்தக பவுடர்: 10 லීட்டர் நீருக்கு 30-40 கிராம்; ஹெக்சா கோனசோல்: 10 லீட்டர் நீருக்கு 10-15 மில்லி.',
    'Spray thoroughly on both upper and lower leaf surfaces at first sign of white powdery spots.': 'வெள்ளை புள்ளிகள் கண்டறியப்பட்டவுடன் இலையின் மேல் மற்றும் அடிப்பகுதிகளில் நன்றாகத் தெளிக்கவும்.',
    'Available islandwide. Common brands: Sulcox (Lankem), Eraze (Hayleys), Shavit (CIC).': 'நாடு முழுவதும் கிடைக்கும். பொதுவான பிராண்டுகள்: Sulcox (Lankem), Eraze (Hayleys), Shavit (CIC).',
    'Do not apply sulfur during temperatures exceeding 32 degrees C as it may cause leaf burn.': 'வெப்பநிலை 32 டிகிரிக்கு மேல் இருக்கும்போது கந்தகத்தைப் பயன்படுத்த வேண்டாம், இது இலைகளை எரித்துவிடும்.',

    'Weekly manual removal and destruction of wilted shoots and infected fruits. Use pheromone traps (Lucilure, 10-12 traps per acre). Spray Neem Seed Kernel Extract (NSKE 5%).': 'வாடிய தண்டுகள் மற்றும் பாதிக்கப்பட்ட காய்களை வாரம் ஒருமுறை அகற்றி அழிக்கவும். பெரோமோன் பொறிகளைப் பயன்படுத்தவும். வேப்பம்பருப்பு சாறு தெளிக்கவும்.',
    'Spray systemic insecticides like Chlorantraniliprole, Spinosad, or Emamectin Benzoate.': 'ஸ்பினோசாட் அல்லது எமாமெக்டின் பென்சோயேட் போன்ற பூச்சிக்கொல்லிகளைத் தெளிக்கவும்.',
    'Coragen (Chlorantraniliprole): 3ml in 10L water; Spinosad: 4ml in 10L water.': 'Coragen: 10 லீட்டர் நீருக்கு 3 மில்லி; ஸ்பினோசாட்: 10 லீட்டர் நீருக்கு 4 மில்லி.',
    'Spray at the initiation of shoot wilting, targeting the terminal shoots and young developing fruits.': 'தண்டுகள் வாடத் தொடங்கும் போது, நுனித் தண்டுகள் மற்றும் இளம் காய்களை இலக்காகக் கொண்டு தெளிக்கவும்.',
    'Available at local agro-input shops. Brands: Coragen (FMC/CIC), Tracer (Dow/Hayleys).': 'உள்ளூர் விவசாய கடைகளில் கிடைக்கும். பிராண்டுகள்: Coragen (CIC), Tracer (Hayleys).',
    'Rotate insecticide chemical classes to prevent pest resistance. Observe a PHI of 3 days.': 'பூச்சிகள் எதிர்ப்புத் திறனைப் பெறுவதைத் தடுக்க பூச்சிக்கொல்லி வகைகளை மாற்றிப் பயன்படுத்தவும். PHI 3 நாட்கள்.',

    'Pull out and burn infected plants immediately. Keep the field free of weed hosts. Use yellow sticky traps to capture leafhopper vectors.': 'பாதிக்கப்பட்ட செடிகளை உடனடியாக அகற்றி எரிக்கவும். வயலை களைகள் இல்லாமல் பராமரிக்கவும். இலை தத்துப்பூச்சிகளைப் பிடிக்க மஞ்சள் ஒட்டும் பொறிகளைப் பயன்படுத்தவும்.',
    'Apply systemic insecticides to control the leafhopper vector, such as Thiamethoxam or Imidacloprid.': 'தத்துப்பூச்சிகளைக் கட்டுப்படுத்த இமிடா குளோபிரிட் போன்ற பூச்சிக்கொல்லிகளைப் பயன்படுத்தவும்.',
    'Imidacloprid: 6ml in 10L water; Thiamethoxam: 5g in 10L water.': 'இமிடா குளோபிரிட்: 10 லீட்டர் நீருக்கு 6 மில்லி; தியாமெதோக்சம்: 10 லீட்டர் நீருக்கு 5 கிராம்.',
    'Spray early in the morning when leafhoppers are less active, targeting vegetative parts.': 'பூச்சிகள் குறைவாகச் செயல்படும் அதிகாலை வேளையில் தாவரப் பகுதிகளை இலக்காகக் கொண்டு தெளிக்கவும்.',
    'Available islandwide. Brands: Admire (Hayleys), Actara (CIC), Lankem Imidacloprid.': 'நாடு முழுவதும் கிடைக்கும். பிராண்டுகள்: Admire (Hayleys), Actara (CIC).',
    'Do not spray when honeybees are actively foraging to protect pollinators.': 'தேனீக்கள் சுறுசுறுப்பாக இருக்கும் நேரங்களில் தெளிப்பதைத் தவிர்க்கவும்.',

    'Practice crop rotation with non-solanaceous crops for 3-4 years. Use soil solarization. Apply organic compost enriched with Trichoderma species.': 'வසර 3-4 ක් மாற்றுப் பயிர் சுழற்சியை மேற்கொள்ளவும். மண்ணைச் சூடாக்கவும். டிரைக்கோடெர்மா கலந்த கரிம உரங்களை இடவும்.',
    'No effective chemical cure exists. Drenching the soil with Carbendazim around healthy plants in infected zones can suppress soil-borne inoculum.': 'பயனுள்ள இரசாயன சிகிச்சை எதுவும் இல்லை. பாதிக்கப்பட்ட செடிகளைச் சுற்றியுள்ள ஆரோக்கியமான செடிகளின் வேரில் கார்பென்டாசிம் ஊற்றுவதன் மூலம் பரவலைத் தடுக்கலாம்.',
    'Carbendazim: 15g in 10L water.': 'கார்பென்டாசிம்: 10 லீட்டர் நீருக்கு 15 கிராம்.',
    'Drench the soil surrounding adjacent healthy plants when wilted patches appear in the field.': 'வயலில் வாடிய செடிகள் தோன்றும் போது அதற்கு அருகிலுள்ள ஆரோக்கியமான செடிகளின் வேர் மண்ணை நனைக்கவும்.',
    'Available at local dealers. Brands: Lankem Carbendazim, CIC Carbendazim, Hayleys Carbendazim.': 'உள்ளூர் கடைகளில் கிடைக்கும். பிராண்டுகள்: Lankem Carbendazim, CIC Carbendazim.',
    'Use strictly as a soil drench. Avoid skin contact and wear protective footwear.': 'மண்ணில் ஊற்றுவதற்கு மட்டுமே பயன்படுத்தவும். தோலில் படாமல் பாதுகாக்கவும்.',

    'Provide trellis support to elevate vines and improve ventilation. Keep plant spacing wide. Avoid overhead watering. Spray copper oxychloride.': 'வாතාශிரயத்தை மேம்படுத்த கொடிகளுக்கு பந்தல் அமைக்கவும். செடிகளுக்கு இடையில் இடைவெளியை விடுங்கள். இலைகளின் மேல் நீர் தெளிப்பதைத் தவிர்க்கவும்.',
    'Apply systemic combination fungicides like Metalaxyl + Mancozeb, or Propamocarb Hydrochloride.': 'மெட்டாலக்சில் + மேன்கோசெப் போன்ற பூஞ்சைக் கொல்லிகளைப் பயன்படுத்தவும்.',
    'Ridomil Gold (Metalaxyl + Mancozeb): 25g in 10L water.': 'ரிடோமில் கோல்ட்: 10 லீட்டர் நீருக்கு 25 கிராம்.',
    'Apply weekly during cool, wet, and cloudy conditions when downy mildew spreads rapidly.': 'நோய் வேகமாகப் பரவும் குளிர் மற்றும் மேகமூட்டமான காலங்களில் வாரந்தோறும் தெளிக்கவும்.',
    'Available at all agricultural stores. Brands: Ridomil Gold (CIC), Lankem Mancozeb.': 'அனைத்து விவசாய கடைகளிலும் கிடைக்கும். பிராண்டுகள்: Ridomil Gold (CIC), Lankem Mancozeb.',
    'Observe a pre-harvest interval (PHI) of 7 days before picking cucumbers.': 'வெள்ளரிக்காய் பறிப்பதற்கு 7 நாட்களுக்கு முன்பு தெளிப்பதை நிறுத்துங்கள் (PHI).',

    'Control aphid vectors using yellow sticky traps and neem oil. Eradicate and burn infected vines. Keep field borders clear of wild weed hosts.': 'மஞ்சள் ஒட்டும் பொறிகள் மற்றும் வேப்ப எண்ணெய் மூலம் அசுவினிகளைக் கட்டுப்படுத்தவும். பாதிக்கப்பட்ட கொடிகளை எரிக்கவும். களைகளை அகற்றவும்.',
    'Control aphid populations using contact or systemic insecticides like Acetamiprid or Imidacloprid.': 'அசிடாமிபிரிட் அல்லது இமிடா குளோபிரிட் போன்ற பூச்சிக்கொல்லிகளைப் பயன்படுத்தி அசுவினிகளைக் கட்டுப்படுத்தவும்.',
    'Acetamiprid: 5g in 10L water; Imidacloprid: 5ml in 10L water.': 'அசிடாமிபிரிட்: 10 லீட்டர் நீருக்கு 5 கிராம்; இமிடா குளோபிரிட்: 10 லீட்டர் நீருக்கு 5 மில்லி.',
    'Spray target aphid colonies under leaves. Apply in the late evening to protect pollinating bees.': 'இலைகளின் அடியில் உள்ள அசுவினி கூட்டங்களைத் தெளிக்கவும். தேனீக்களைப் பாதுகாக்க மாலை நேரத்தில் தெளிக்கவும்.',
    'Available at local agrochemical stores. Brands: Mospilan (Lankem), Admire (Hayleys), Actara (CIC).': 'விவசாய கடைகளில் கிடைக்கும். பிராண்டுகள்: Mospilan (Lankem), Admire (Hayleys).',
    'Cucumber plants depend heavily on bees for pollination. Avoid spraying chemicals during flowering daytime hours.': 'வெள்ளரிப் பயிர் மகரந்தச் சேர்க்கைக்கு தேனீக்களை நம்பியிருப்பதால், பூக்கும் நேரத்தில் தெளிப்பதைத் தவிர்க்கவும்.',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    if (!key) return '';
    
    const cleanKey = key.trim();
    
    // Check if key is a dynamic database content
    if (language !== 'en' && contentTranslations[language]?.[cleanKey]) {
      return contentTranslations[language][cleanKey];
    }
    
    // Check if key is a static UI label
    if (uiTranslations[language]?.[cleanKey]) {
      return uiTranslations[language][cleanKey];
    }
    
    // Fallback to the key itself (which is in English)
    if (uiTranslations['en']?.[cleanKey]) {
      return uiTranslations['en'][cleanKey];
    }
    
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
